# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

{ lib, nodejs, stdenv, fetchurl, writeText }:
{ src, symlinkPackages ? false, overrideAttrs ? null, netrcFilePath ? null, envVarNamesToPathStrings ? null, ... } @ args:

let

  yarnPath = ./.yarn/releases/yarn-berry.cjs;
  yarnPathString = "./.yarn/releases/yarn-berry.cjs";
  yarnLock = ./yarn.lock;
  packageJson = ./package.json;
  yarnrcYaml = builtins.path {
    path = ./.yarnrc.yml;
    name = "yarnrc.yml";
  };
  yarnPlugins = builtins.path {
    path = ./.yarn/plugins;
    name = "yarnPlugins";
  };

  cacheFolder = ".yarn/cache";

  # Call overrideAttrs on a derivation if a function is provided.
  optionalOverride = fn: drv:
    if fn == null then drv else drv.overrideAttrs fn;

  # Common attributes between Yarn derivations.
  drvCommon = {
    # Make sure the build uses the right Node.js version everywhere.
    buildInputs = [ nodejs ];
    # Tell node-gyp to use the provided Node.js headers for native code builds.
    npm_config_nodedir = nodejs;
    # Tell node-pre-gyp to never fetch binaries / always build from source.
    npm_config_build_from_source = "true";
    # Defines the shell alias to run Yarn.
    postHook = ''
      yarn() {
        CI=1 node "${yarnPath}" "$@"
      }
    '';
  };

  # Create derivations for fetching dependencies.
  cacheDrvs = let
    builder = builtins.toFile "builder.sh" ''
      source $stdenv/setup
      ${
        if envVarNamesToPathStrings != null
        # build a list of export statement
        then lib.concatStringsSep "\n" (lib.mapAttrsToList
          (name: path: "export ${name}=$(cat ${path})")
          envVarNamesToPathStrings
        )
        else ""
      }

      yarn_cache_dir=$TMP

      cd $TMP
      ln -s ${yarnLock} yarn.lock
      ln -s ${packageJson} package.json
      ln -s ${yarnrcYaml} .yarnrc.yml
      ln -s ${yarnPlugins} .yarn/plugins

      mkdir -p $(dirname yarnPathString)
      echo yarnPath: ${yarnPath}
      echo yarnPathString: ${yarnPathString}
      ln -s ${yarnPath} ${yarnPathString}

      echo ls .yarn
      ls .yarn

      HOME="$TMP" \
        yarn_cache_folder="$yarn_cache_dir" \
        CI=1 \
        node ${yarnPath} nixify fetch-one $locator

      # Because we change the cache dir, Yarn may generate a different name.
      mv "$yarn_cache_dir/$(sed 's/-[^-]*\.[^-]*$//' <<< "$outputFilename")"-* $out
    '';
  in lib.mapAttrs (locator: { filename, sha512 }: stdenv.mkDerivation {
    inherit src builder locator;
    name = lib.strings.sanitizeDerivationName locator;
    buildInputs = [ nodejs ];
    outputFilename = filename;
    outputHashMode = "flat";
    outputHashAlgo = "sha512";
    outputHash = sha512;
  }) cacheEntries;

  # Create a shell snippet to copy dependencies from a list of derivations.
  mkCacheBuilderForDrvs = drvs:
    writeText "collect-cache.sh" (lib.concatMapStrings (drv: ''
      ${if symlinkPackages then "ln -s" else "cp"} ${drv} '${drv.outputFilename}'
    '') drvs);

  # Create a shell snippet to copy dependencies from a list of locators.
  mkCacheBuilderForLocators = let
    pickCacheDrvs = map (locator: cacheDrvs.${locator});
  in locators:
    mkCacheBuilderForDrvs (pickCacheDrvs locators);

  # Create a derivation that builds a node-pre-gyp module in isolation.
  mkIsolatedBuild = { pname, version, locators }: stdenv.mkDerivation (drvCommon // {
    inherit pname version;
    phases = [ "buildPhase" "installPhase" ];

    buildPhase = ''
      mkdir -p .yarn/cache
      pushd .yarn/cache > /dev/null
      source ${mkCacheBuilderForLocators locators}
      popd > /dev/null

      echo '{ "dependencies": { "${pname}": "${version}" } }' > package.json
      install -m 0600 ${yarnLock} ./yarn.lock
      export yarn_global_folder="$TMP"
      export YARN_ENABLE_IMMUTABLE_INSTALLS=false
      yarn --immutable-cache
    '';

    installPhase = ''
      unplugged=( .yarn/unplugged/${pname}-*/node_modules/* )
      if [[ ! -e "''${unplugged[@]}" ]]; then
        echo >&2 "Could not find the unplugged path for ${pname}"
        exit 1
      fi

      mv "$unplugged" $out
    '';
  });

  # Main project derivation.
  project = stdenv.mkDerivation (drvCommon // {
    inherit src;
    name = "yarn-3-test";
    # Disable Nixify plugin to save on some unnecessary processing.
    yarn_enable_nixify = "false";

    configurePhase = ''
      # Copy over the Yarn cache.
      rm -fr '${cacheFolder}'
      mkdir -p '${cacheFolder}'
      pushd '${cacheFolder}' > /dev/null
      source ${mkCacheBuilderForDrvs (lib.attrValues cacheDrvs)}
      popd > /dev/null

      # Yarn may need a writable home directory.
      export yarn_global_folder="$TMP"

      # Some node-gyp calls may call out to npm, which could fail due to an
      # read-only home dir.
      export HOME="$TMP"

      # running preConfigure after the cache is populated allows for
      # preConfigure to contain substituteInPlace for dependencies as well as the
      # main project. This is necessary for native bindings that maybe have
      # hardcoded values.
      runHook preConfigure

      # Copy in isolated builds.
      echo 'injecting build for keccak'
      yarn nixify inject-build \
        "keccak@npm:3.0.2" \
        ${isolated."keccak@npm:3.0.2"} \
        ".yarn/unplugged/keccak-npm-3.0.2-6e9dec8765/node_modules/keccak"
      echo 'running yarn install'

      # Run normal Yarn install to complete dependency installation.
      yarn install --immutable --immutable-cache

      runHook postConfigure
    '';

    buildPhase = ''
      runHook preBuild
      runHook postBuild
    '';

    installPhase = ''
      runHook preInstall

      mkdir -p $out/libexec $out/bin

      # Move the entire project to the output directory.
      mv $PWD "$out/libexec/$sourceRoot"
      cd "$out/libexec/$sourceRoot"

      # Invoke a plugin internal command to setup binaries.
      yarn nixify install-bin $out/bin

      runHook postInstall
    '';

    passthru = {
      inherit nodejs;
    };
  });

cacheEntries = {
"@adrian-gierakowski/private-repo-test@npm:1.0.1::__archiveUrl=https%3A%2F%2Fnpm.pkg.github.com%2Fdownload%2F%40adrian-gierakowski%2Fprivate-repo-test%2F1.0.1%2F0eb9f0ef93548304655df1f8f4b56128232363632684b17b58662232456c4f02" = { filename = "@adrian-gierakowski-private-repo-test-npm-1.0.1-79349c8bea-5fd1bbd761.zip"; sha512 = "5fd1bbd761b281a0e573c2ec2a1f169f82ab95b412ba20fe7f4c82d2db072166287be3125d7ea9338c3bdb43b68b70fffe00c7a2559f685bd6f77c1318f38f7a"; };
"node-module-test@https://github.com/adrian-gierakowski/node-module-test.git#commit=744e3e4968c7a4141b5f09ab48f4d510b5638afb" = { filename = "node-module-test-https-3e33dc2311-ea431dd65e.zip"; sha512 = "ea431dd65ec05c8510dda143aa7efa3d0ea0a21c8649e9d8783de2e1df79dce3fc6271530861dcb99e21d6830702e24f1593ef2ab09b37fd3c02a46589be2343"; };
"keccak@npm:3.0.2" = { filename = "keccak-npm-3.0.2-6e9dec8765-39a7d6128b.zip"; sha512 = "39a7d6128b8ee4cb7dcd186fc7e20c6087cc39f573a0f81b147c323f688f1f7c2b34f62c4ae189fe9b81c6730b2d1228d8a399cdc1f3d8a4c8f030cdc4f20272"; };
"node-gyp-build@npm:4.3.0" = { filename = "node-gyp-build-npm-4.3.0-87bdf5216f-1ecab16d9f.zip"; sha512 = "1ecab16d9f275174d516e223f60f65ebe07540347d5c04a6a7d6921060b7f2e3af4f19463d9d1dcedc452e275c2ae71354a99405e55ebd5b655bb2f38025c728"; };
"node-addon-api@npm:2.0.2" = { filename = "node-addon-api-npm-2.0.2-8c2c1e9782-31fb22d674.zip"; sha512 = "31fb22d674648204f8dd94167eb5aac896c841b84a9210d614bf5d97c74ef059cc6326389cf0c54d2086e35312938401d4cc82e5fcd679202503eb8ac84814f8"; };
"readable-stream@npm:3.6.0" = { filename = "readable-stream-npm-3.6.0-23a4a5eb56-d4ea81502d.zip"; sha512 = "d4ea81502d3799439bb955a3a5d1d808592cf3133350ed352aeaa499647858b27b1c4013984900238b0873ec8d0d8defce72469fb7a83e61d53f5ad61cb80dc8"; };
"inherits@npm:2.0.4" = { filename = "inherits-npm-2.0.4-c66b3957a0-4a48a73384.zip"; sha512 = "4a48a733847879d6cf6691860a6b1e3f0f4754176e4d71494c41f3475553768b10f84b5ce1d40fbd0e34e6bfbb864ee35858ad4dd2cf31e02fc4a154b724d7f1"; };
"util-deprecate@npm:1.0.2" = { filename = "util-deprecate-npm-1.0.2-e3fe1a219c-474acf1146.zip"; sha512 = "474acf1146cb2701fe3b074892217553dfcf9a031280919ba1b8d651a068c9b15d863b7303cb15bd00a862b498e6cf4ad7b4a08fb134edd5a6f7641681cb54a2"; };
"string_decoder@npm:1.3.0" = { filename = "string_decoder-npm-1.3.0-2422117fd0-8417646695.zip"; sha512 = "8417646695a66e73aefc4420eb3b84cc9ffd89572861fe004e6aeb13c7bc00e2f616247505d2dbbef24247c372f70268f594af7126f43548565c68c117bdeb56"; };
"node-gyp@npm:8.4.1" = { filename = "node-gyp-npm-8.4.1-13c90a9c9b-341710b5da.zip"; sha512 = "341710b5da39d3660e6a886b37e210d33f8282047405c2e62c277bcc744c7552c5b8b972ebc3a7d5c2813794e60cc48c3ebd142c46d6e0321db4db6c92dd0355"; };
"safe-buffer@npm:5.2.1" = { filename = "safe-buffer-npm-5.2.1-3481c8aa9b-b99c4b41fd.zip"; sha512 = "b99c4b41fdd67a6aaf280fcd05e9ffb0813654894223afb78a31f14a19ad220bba8aba1cb14eddce1fcfb037155fe6de4e861784eb434f7d11ed58d1e70dd491"; };
"env-paths@npm:2.2.1" = { filename = "env-paths-npm-2.2.1-7c7577428c-65b5df55a8.zip"; sha512 = "65b5df55a8bab92229ab2b40dad3b387fad24613263d103a97f91c9fe43ceb21965cd3392b1ccb5d77088021e525c4e0481adb309625d0cb94ade1d1fb8dc17e"; };
"graceful-fs@npm:4.2.9" = { filename = "graceful-fs-npm-4.2.9-ee48e00aaa-68ea4e07ff.zip"; sha512 = "68ea4e07ff2c041ada184f9278b830375f8e0b75154e3f080af6b70f66172fabb4108d19b3863a96b53fc068a310b9b6493d86d1291acc5f3861eb4b79d26ad6"; };
"nopt@npm:5.0.0" = { filename = "nopt-npm-5.0.0-304b40fbfe-d35fdec187.zip"; sha512 = "d35fdec187269503843924e0114c0c6533fb54bbf1620d0f28b4b60ba01712d6687f62565c55cc20a504eff0fbe5c63e22340c3fad549ad40469ffb611b04f2f"; };
"rimraf@npm:3.0.2" = { filename = "rimraf-npm-3.0.2-2cb7dac69a-87f4164e39.zip"; sha512 = "87f4164e396f0171b0a3386cc1877a817f572148ee13a7e113b238e48e8a9f2f31d009a92ec38a591ff1567d9662c6b67fd8818a2dbbaed74bc26a87a2a4a9a0"; };
"semver@npm:7.3.5" = { filename = "semver-npm-7.3.5-618cf5db6a-5eafe6102b.zip"; sha512 = "5eafe6102bea2a7439897c1856362e31cc348ccf96efd455c8b5bc2c61e6f7e7b8250dc26b8828c1d76a56f818a7ee907a36ae9fb37a599d3d24609207001d60"; };
"which@npm:2.0.2" = { filename = "which-npm-2.0.2-320ddf72f7-1a5c563d3c.zip"; sha512 = "1a5c563d3c1b52d5f893c8b61afe11abc3bab4afac492e8da5bde69d550de701cf9806235f20a47b5c8fa8a1d6a9135841de2596535e998027a54589000e66d1"; };
"npmlog@npm:6.0.0" = { filename = "npmlog-npm-6.0.0-94a534434f-33d8a7fe3d.zip"; sha512 = "33d8a7fe3d63bf83b16655b6588ae7ba10b5f37b067a661e7cab6508660d7c3204ae716ee2c5ce4eb9626fd1489cf2fa7645d789bc3b704f8c3ccb04a532a50b"; };
"abbrev@npm:1.1.1" = { filename = "abbrev-npm-1.1.1-3659247eab-a4a97ec07d.zip"; sha512 = "a4a97ec07d7ea112c517036882b2ac22f3109b7b19077dc656316d07d308438aac28e4d9746dc4d84bf6b1e75b4a7b0a5f3cb30592419f128ca9a8cee3bcfa17"; };
"isexe@npm:2.0.0" = { filename = "isexe-npm-2.0.0-b58870bd2e-26bf6c5480.zip"; sha512 = "26bf6c5480dda5161c820c5b5c751ae1e766c587b1f951ea3fcfc973bafb7831ae5b54a31a69bd670220e42e99ec154475025a468eae58ea262f813fdc8d1c62"; };
"lru-cache@npm:6.0.0" = { filename = "lru-cache-npm-6.0.0-b4c8668fe1-f97f499f89.zip"; sha512 = "f97f499f898f23e4585742138a22f22526254fdba6d75d41a1c2526b3b6cc5747ef59c5612ba7375f42aca4f8461950e925ba08c991ead0651b4918b7c978297"; };
"glob@npm:7.2.0" = { filename = "glob-npm-7.2.0-bb4644d239-78a8ea9423.zip"; sha512 = "78a8ea942331f08ed2e055cb5b9e40fe6f46f579d7fd3d694f3412fe5db23223d29b7fee1575440202e9a7ff9a72ab106a39fee39934c7bedafe5e5f8ae20134"; };
"tar@npm:6.1.11" = { filename = "tar-npm-6.1.11-e6ac3cba9c-a04c07bb9e.zip"; sha512 = "a04c07bb9e2d8f46776517d4618f2406fb977a74d914ad98b264fc3db0fe8224da5bec11e5f8902c5b9bcb8ace22d95fbe3c7b36b8593b7dfc8391a25898f32f"; };
"console-control-strings@npm:1.1.0" = { filename = "console-control-strings-npm-1.1.0-e3160e5275-8755d76787.zip"; sha512 = "8755d76787f94e6cf79ce4666f0c5519906d7f5b02d4b884cf41e11dcd759ed69c57da0670afd9236d229a46e0f9cf519db0cd829c6dca820bb5a5c3def584ed"; };
"set-blocking@npm:2.0.0" = { filename = "set-blocking-npm-2.0.0-49e2cffa24-6e65a05f7c.zip"; sha512 = "6e65a05f7cf7ebdf8b7c75b101e18c0b7e3dff4940d480efed8aad3a36a4005140b660fa1d804cb8bce911cac290441dc728084a30504d3516ac2ff7ad607b02"; };
"yallist@npm:4.0.0" = { filename = "yallist-npm-4.0.0-b493d9e907-343617202a.zip"; sha512 = "343617202af32df2a15a3be36a5a8c0c8545208f3d3dfbc6bb7c3e3b7e8c6f8e7485432e4f3b88da3031a6e20afa7c711eded32ddfb122896ac5d914e75848d5"; };
"fs.realpath@npm:1.0.0" = { filename = "fs.realpath-npm-1.0.0-c8f05d8126-99ddea01a7.zip"; sha512 = "99ddea01a7e75aa276c250a04eedeffe5662bce66c65c07164ad6264f9de18fb21be9433ead460e54cff20e31721c811f4fb5d70591799df5f85dce6d6746fd0"; };
"path-is-absolute@npm:1.0.1" = { filename = "path-is-absolute-npm-1.0.1-31bc695ffd-060840f92c.zip"; sha512 = "060840f92cf8effa293bcc1bea81281bd7d363731d214cbe5c227df207c34cd727430f70c6037b5159c8a870b9157cba65e775446b0ab06fd5ecc7e54615a3b8"; };
"are-we-there-yet@npm:2.0.0" = { filename = "are-we-there-yet-npm-2.0.0-7d2f5201ce-6c80b4fd04.zip"; sha512 = "6c80b4fd04ecee6ba6e737e0b72a4b41bdc64b7d279edfc998678567ff583c8df27e27523bc789f2c99be603ffa9eaa612803da1d886962d2086e7ff6fa90c7c"; };
"chownr@npm:2.0.0" = { filename = "chownr-npm-2.0.0-638f1c9c61-c57cf9dd07.zip"; sha512 = "c57cf9dd0791e2f18a5ee9c1a299ae6e801ff58fee96dc8bfd0dcb4738a6ce58dd252a3605b1c93c6418fe4f9d5093b28ffbf4d66648cb2a9c67eaef9679be2f"; };
"mkdirp@npm:1.0.4" = { filename = "mkdirp-npm-1.0.4-37f6ef56b9-a96865108c.zip"; sha512 = "a96865108c6c3b1b8e1d5e9f11843de1e077e57737602de1b82030815f311be11f96f09cce59bd5b903d0b29834733e5313f9301e3ed6d6f6fba2eae0df4298f"; };
"minimatch@npm:3.0.4" = { filename = "minimatch-npm-3.0.4-6e76f51c23-66ac295f8a.zip"; sha512 = "66ac295f8a7b59788000ea3749938b0970344c841750abd96694f80269b926ebcafad3deeb3f1da2522978b119e6ae3a5869b63b13a7859a456b3408bd18a078"; };
"once@npm:1.4.0" = { filename = "once-npm-1.4.0-ccf03ef07a-cd0a885013.zip"; sha512 = "cd0a88501333edd640d95f0d2700fbde6bff20b3d4d9bdc521bdd31af0656b5706570d6c6afe532045a20bb8dc0849f8332d6f2a416e0ba6d3d3b98806c7db68"; };
"fs-minipass@npm:2.1.0" = { filename = "fs-minipass-npm-2.1.0-501ef87306-1b8d128dae.zip"; sha512 = "1b8d128dae2ac6cc94230cc5ead341ba3e0efaef82dab46a33d171c044caaa6ca001364178d42069b2809c35a1c3c35079a32107c770e9ffab3901b59af8c8b1"; };
"minipass@npm:3.1.6" = { filename = "minipass-npm-3.1.6-f032df1661-57a0404141.zip"; sha512 = "57a04041413a3531a65062452cb5175f93383ef245d6f4a2961d34386eb9aa8ac11ac7f16f791f5e8bbaf1dfb1ef01596870c88e8822215db57aa591a5bb0a77"; };
"inflight@npm:1.0.6" = { filename = "inflight-npm-1.0.6-ccedb4b908-f4f76aa072.zip"; sha512 = "f4f76aa072ce19fae87ce1ef7d221e709afb59d445e05d47fba710e85470923a75de35bfae47da6de1b18afc3ce83d70facf44cfb0aff89f0a3f45c0a0244dfd"; };
"minizlib@npm:2.1.2" = { filename = "minizlib-npm-2.1.2-ea89cd0cfb-f1fdeac0b0.zip"; sha512 = "f1fdeac0b07cf8f30fcf12f4b586795b97be856edea22b5e9072707be51fc95d41487faec3f265b42973a304fe3a64acd91a44a3826a963e37b37bafde0212c3"; };
"delegates@npm:1.0.0" = { filename = "delegates-npm-1.0.0-9b1942d75f-a51744d9b5.zip"; sha512 = "a51744d9b53c164ba9c0492471a1a2ffa0b6727451bdc89e31627fdf4adda9d51277cfcbfb20f0a6f08ccb3c436f341df3e92631a3440226d93a8971724771fd"; };
"wrappy@npm:1.0.2" = { filename = "wrappy-npm-1.0.2-916de4d4b3-159da4805f.zip"; sha512 = "159da4805f7e84a3d003d8841557196034155008f817172d4e986bd591f74aa82aa7db55929a54222309e01079a65a92a9e6414da5a6aa4b01ee44a511ac3ee5"; };
"make-fetch-happen@npm:9.1.0" = { filename = "make-fetch-happen-npm-9.1.0-23184ad7f6-0eb371c85f.zip"; sha512 = "0eb371c85fdd0b1584fcfdf3dc3c62395761b3c14658be02620c310305a9a7ecf1617a5e6fb30c1d081c5c8aaf177fa133ee225024313afabb7aa6a10f1e3d04"; };
"brace-expansion@npm:1.1.11" = { filename = "brace-expansion-npm-1.1.11-fb95eb05ad-faf34a7bb0.zip"; sha512 = "faf34a7bb0c3fcf4b59c7808bc5d2a96a40988addf2e7e09dfbb67a2251800e0d14cd2bfc1aa79174f2f5095c54ff27f46fb1289fe2d77dac755b5eb3434cc07"; };
"gauge@npm:4.0.0" = { filename = "gauge-npm-4.0.0-962bc1259b-637b34c84f.zip"; sha512 = "637b34c84f518defa89319dbef68211a24e9302182ad2a619e3be1be5b7dcf2a962c8359e889294af667440f4722e7e6e61671859e00bd8ec280a136ded89b25"; };
"http-cache-semantics@npm:4.1.0" = { filename = "http-cache-semantics-npm-4.1.0-860520a31f-974de94a81.zip"; sha512 = "974de94a81c5474be07f269f9fd8383e92ebb5a448208223bfb39e172a9dbc26feff250192ecc23b9593b3f92098e010406b0f24bd4d588d631f80214648ed42"; };
"is-lambda@npm:1.0.1" = { filename = "is-lambda-npm-1.0.1-7ab55bc8a8-93a32f0194.zip"; sha512 = "93a32f01940220532e5948538699ad610d5924ac86093fcee83022252b363eb0cc99ba53ab084a04e4fb62bf7b5731f55496257a4c38adf87af9c4d352c71c35"; };
"negotiator@npm:0.6.2" = { filename = "negotiator-npm-0.6.2-ba538e167a-dfddaff6c0.zip"; sha512 = "dfddaff6c06792f1c4c3809e29a427b8daef8cd437c83b08dd51d7ee11bbd1c29d9512d66b801144d6c98e910ffd8723f2432e0cbf8b18d41d2a09599c975ab3"; };
"balanced-match@npm:1.0.2" = { filename = "balanced-match-npm-1.0.2-a53c126459-9706c088a2.zip"; sha512 = "9706c088a283058a8a99e0bf91b0a2f75497f185980d9ffa8b304de1d9e58ebda7c72c07ebf01dadedaac5b2907b2c6f566f660d62bd336c3468e960403b9d65"; };
"concat-map@npm:0.0.1" = { filename = "concat-map-npm-0.0.1-85a921b7ee-902a9f5d89.zip"; sha512 = "902a9f5d8967a3e2faf138d5cb784b9979bad2e6db5357c5b21c568df4ebe62bcb15108af1b2253744844eb964fc023fbd9afbbbb6ddd0bcc204c6fb5b7bf3af"; };
"ansi-regex@npm:5.0.1" = { filename = "ansi-regex-npm-5.0.1-c963a48615-2aa4bb54ca.zip"; sha512 = "2aa4bb54caf2d622f1afdad09441695af2a83aa3fe8b8afa581d205e57ed4261c183c4d3877cee25794443fde5876417d859c108078ab788d6af7e4fe52eb66b"; };
"aproba@npm:2.0.0" = { filename = "aproba-npm-2.0.0-8716bcfde6-5615cadcfb.zip"; sha512 = "5615cadcfb45289eea63f8afd064ab656006361020e1735112e346593856f87435e02d8dcc7ff0d11928bc7d425f27bc7c2a84f6c0b35ab0ff659c814c138a24"; };
"color-support@npm:1.1.3" = { filename = "color-support-npm-1.1.3-3be5c53455-9b73568176.zip"; sha512 = "9b7356817670b9a13a26ca5af1c21615463b500783b739b7634a0c2047c16cef4b2865d7576875c31c3cddf9dd621fa19285e628f20198b233a5cfdda6d0793b"; };
"has-unicode@npm:2.0.1" = { filename = "has-unicode-npm-2.0.1-893adb4747-1eab07a743.zip"; sha512 = "1eab07a7436512db0be40a710b29b5dc21fa04880b7f63c9980b706683127e3c1b57cb80ea96d47991bdae2dfe479604f6a1ba410106ee1046a41d1bd0814400"; };
"signal-exit@npm:3.0.6" = { filename = "signal-exit-npm-3.0.6-66fc2466b6-b819ac81ba.zip"; sha512 = "b819ac81ba757af559dad0804233ae31bf6f054591cd8a671e9cbcf09f21c72ec3076fe87d1e04861f5b33b47d63f0694b568de99c99cd733ee2060515beb6d5"; };
"minipass-collect@npm:1.0.2" = { filename = "minipass-collect-npm-1.0.2-3b4676eab5-14df761028.zip"; sha512 = "14df761028f3e47293aee72888f2657695ec66bd7d09cae7ad558da30415fdc4752bbfee66287dcc6fd5e6a2fa3466d6c484dc1cbd986525d9393b9523d97f10"; };
"minipass-flush@npm:1.0.5" = { filename = "minipass-flush-npm-1.0.5-efe79d9826-56269a0b22.zip"; sha512 = "56269a0b22bad756a08a94b1ffc36b7c9c5de0735a4dd1ab2b06c066d795cfd1f0ac44a0fcae13eece5589b908ecddc867f04c745c7009be0b566421ea0944cf"; };
"minipass-pipeline@npm:1.2.4" = { filename = "minipass-pipeline-npm-1.2.4-5924cb077f-b14240dac0.zip"; sha512 = "b14240dac0d29823c3d5911c286069e36d0b81173d7bdf07a7e4a91ecdef92cdff4baaf31ea3746f1c61e0957f652e641223970870e2353593f382112257971b"; };
"ssri@npm:8.0.1" = { filename = "ssri-npm-8.0.1-a369e72ce2-bc447f5af8.zip"; sha512 = "bc447f5af814fa9713aa201ec2522208ae0f4d8f3bda7a1f445a797c7b929a02720436ff7c478fb5edc4045adb02b1b88d2341b436a80798734e2494f1067b36"; };
"strip-ansi@npm:6.0.1" = { filename = "strip-ansi-npm-6.0.1-caddc7cb40-f3cd25890a.zip"; sha512 = "f3cd25890aef3ba6e1a74e20896c21a46f482e93df4a06567cebf2b57edabb15133f1f94e57434e0a958d61186087b1008e89c94875d019910a213181a14fc8c"; };
"wide-align@npm:1.1.5" = { filename = "wide-align-npm-1.1.5-889d77e592-d5fc37cd56.zip"; sha512 = "d5fc37cd561f9daee3c80e03b92ed3e84d80dde3365a8767263d03dacfc8fa06b065ffe1df00d8c2a09f731482fcacae745abfbb478d4af36d0a891fad4834d3"; };
"https-proxy-agent@npm:5.0.0" = { filename = "https-proxy-agent-npm-5.0.0-bb777903c3-165bfb090b.zip"; sha512 = "165bfb090bd26d47693597661298006841ab733d0c7383a8cb2f17373387a94c903a3ac687090aa739de05e379ab6f868bae84ab4eac288ad85c328cd1ec9e53"; };
"promise-retry@npm:2.0.1" = { filename = "promise-retry-npm-2.0.1-871f0b01b7-f96a3f6d90.zip"; sha512 = "f96a3f6d90b92b568a26f71e966cbbc0f63ab85ea6ff6c81284dc869b41510e6cdef99b6b65f9030f0db422bf7c96652a3fff9f2e8fb4a0f069d8f4430359429"; };
"agentkeepalive@npm:4.2.0" = { filename = "agentkeepalive-npm-4.2.0-e5e72b8ce4-89806f83ce.zip"; sha512 = "89806f83ceebbcaabf6bd581a8dce4870910fd2a11f66df8f505b4cd4ce4ca5ab9e6eec8d11ce8531a6b60f6748b75b0775e0e2fa33871503ef00d535418a19a"; };
"http-proxy-agent@npm:4.0.1" = { filename = "http-proxy-agent-npm-4.0.1-ce9ef61788-c6a5da5a19.zip"; sha512 = "c6a5da5a1929416b6bbdf77b1aca13888013fe7eb9d59fc292e25d18e041bb154a8dfada58e223fc7b76b9b2d155a87e92e608235201f77d34aa258707963a82"; };
"socks-proxy-agent@npm:6.1.1" = { filename = "socks-proxy-agent-npm-6.1.1-a3843946ba-9a8a4f791b.zip"; sha512 = "9a8a4f791bba0060315cf7291ca6f9db37d6fc280fd0860d73d8887d3efe4c22e823aa25a8d5375f6079279f8dc91b50c075345179bf832bfe3c7c26d3582e3c"; };
"string-width@npm:4.2.3" = { filename = "string-width-npm-4.2.3-2c27177bae-e52c10dc3f.zip"; sha512 = "e52c10dc3fbfcd6c3a15f159f54a90024241d0f149cf8aed2982a2d801d2e64df0bf1dc351cf8e95c3319323f9f220c16e740b06faecd53e2462df1d2b5443fb"; };
"minipass-fetch@npm:1.4.1" = { filename = "minipass-fetch-npm-1.4.1-2d67357feb-ec93697bdb.zip"; sha512 = "ec93697bdb62129c4e6c0104138e681e30efef8c15d9429dd172f776f83898471bc76521b539ff913248cc2aa6d2b37b652c993504a51cc53282563640f29216"; };
"err-code@npm:2.0.3" = { filename = "err-code-npm-2.0.3-082e0ff9a7-8b7b1be20d.zip"; sha512 = "8b7b1be20d2de12d2255c0bc2ca638b7af5171142693299416e6a9339bd7d88fc8d7707d913d78e0993176005405a236b066b45666b27b797252c771156ace54"; };
"retry@npm:0.12.0" = { filename = "retry-npm-0.12.0-72ac7fb4cc-623bd7d2e5.zip"; sha512 = "623bd7d2e5119467ba66202d733ec3c2e2e26568074923bc0585b6b99db14f357e79bdedb63cab56cec47491c4a0da7e6021a7465ca6dc4f481d3898fdd3158c"; };
"depd@npm:1.1.2" = { filename = "depd-npm-1.1.2-b0c8414da7-6b406620d2.zip"; sha512 = "6b406620d269619852885ce15965272b829df6f409724415e0002c8632ab6a8c0a08ec1f0bd2add05dc7bd7507606f7e2cc034fa24224ab829580040b835ecd9"; };
"@tootallnate/once@npm:1.1.2" = { filename = "@tootallnate-once-npm-1.1.2-0517220057-e1fb1bbbc1.zip"; sha512 = "e1fb1bbbc12089a0cb9433dc290f97bddd062deadb6178ce9bcb93bb7c1aecde5e60184bc7065aec42fe1663622a213493c48bbd4972d931aae48315f18e1be9"; };
"agent-base@npm:6.0.2" = { filename = "agent-base-npm-6.0.2-428f325a93-f52b6872cc.zip"; sha512 = "f52b6872cc96fd5f622071b71ef200e01c7c4c454ee68bc9accca90c98cfb39f2810e3e9aa330435835eedc8c23f4f8a15267f67c6e245d2b33757575bdac49d"; };
"debug@npm:4.3.3" = { filename = "debug-npm-4.3.3-710fd4cc7f-14472d56fe.zip"; sha512 = "14472d56fe4a94dbcfaa6dbed2dd3849f1d72ba78104a1a328047bb564643ca49df0224c3a17fa63533fd11dd3d4c8636cd861191232a2c6735af00cc2d4de16"; };
"emoji-regex@npm:8.0.0" = { filename = "emoji-regex-npm-8.0.0-213764015c-d4c5c39d5a.zip"; sha512 = "d4c5c39d5a9868b5fa152f00cada8a936868fd3367f33f71be515ecee4c803132d11b31a6222b2571b1e5f7e13890156a94880345594d0ce7e3c9895f560f192"; };
"is-fullwidth-code-point@npm:3.0.0" = { filename = "is-fullwidth-code-point-npm-3.0.0-1ecf4ebee5-44a30c2945.zip"; sha512 = "44a30c29457c7fb8f00297bce733f0a64cd22eca270f83e58c105e0d015e45c019491a4ab2faef91ab51d4738c670daff901c799f6a700e27f7314029e99e348"; };
"humanize-ms@npm:1.2.1" = { filename = "humanize-ms-npm-1.2.1-e942bd7329-9c7a74a282.zip"; sha512 = "9c7a74a2827f9294c009266c82031030eae811ca87b0da3dceb8d6071b9bde22c9f3daef0469c3c533cc67a97d8a167cd9fc0389350e5f415f61a79b171ded16"; };
"encoding@npm:0.1.13" = { filename = "encoding-npm-0.1.13-82a1837d30-bb98632f8f.zip"; sha512 = "bb98632f8ffa823996e508ce6a58ffcf5856330fde839ae42c9e1f436cc3b5cc651d4aeae72222916545428e54fd0f6aa8862fd8d25bdbcc4589f1e3f3715e7f"; };
"minipass-sized@npm:1.0.3" = { filename = "minipass-sized-npm-1.0.3-306d86f432-79076749fc.zip"; sha512 = "79076749fcacf21b5d16dd596d32c3b6bf4d6e62abb43868fac21674078505c8b15eaca4e47ed844985a4514854f917d78f588fcd029693709417d8f98b2bd60"; };
"socks@npm:2.6.1" = { filename = "socks-npm-2.6.1-09133d0d22-2ca9d616e4.zip"; sha512 = "2ca9d616e424f645838ebaabb04f85d94ea999e0f8393dc07f86c435af22ed88cb83958feeabd1bb7bc537c635ed47454255635502c6808a6df61af1f41af750"; };
"ms@npm:2.1.2" = { filename = "ms-npm-2.1.2-ec0c1512ff-673cdb2c31.zip"; sha512 = "673cdb2c3133eb050c745908d8ce632ed2c02d85640e2edb3ace856a2266a813b30c613569bf3354fdf4ea7d1a1494add3bfa95e2713baa27d0c2c71fc44f58f"; };
"ms@npm:2.1.3" = { filename = "ms-npm-2.1.3-81ff3cfac1-aa92de6080.zip"; sha512 = "aa92de608021b242401676e35cfa5aa42dd70cbdc082b916da7fb925c542173e36bce97ea3e804923fe92c0ad991434e4a38327e15a1b5b5f945d66df615ae6d"; };
"ip@npm:1.1.5" = { filename = "ip-npm-1.1.5-af36318aa6-30133981f0.zip"; sha512 = "30133981f082a060a32644f6a7746e9ba7ac9e2bc07ecc8bbdda3ee8ca9bec1190724c390e45a1ee7695e7edfd2a8f7dda2c104ec5f7ac5068c00648504c7e5a"; };
"smart-buffer@npm:4.2.0" = { filename = "smart-buffer-npm-4.2.0-5ac3f668bb-b5167a7142.zip"; sha512 = "b5167a7142c1da704c0e3af85c402002b597081dd9575031a90b4f229ca5678e9a36e8a374f1814c8156a725d17008ae3bde63b92f9cfd132526379e580bec8b"; };
"iconv-lite@npm:0.6.3" = { filename = "iconv-lite-npm-0.6.3-24b8aae27e-3f60d47a5c.zip"; sha512 = "3f60d47a5c8fc3313317edfd29a00a692cc87a19cac0159e2ce711d0ebc9019064108323b5e493625e25594f11c6236647d8e256fbe7a58f4a3b33b89e6d30bf"; };
"safer-buffer@npm:2.1.2" = { filename = "safer-buffer-npm-2.1.2-8d5c0b705e-cab8f25ae6.zip"; sha512 = "cab8f25ae6f1434abee8d80023d7e72b598cf1327164ddab31003c51215526801e40b66c5e65d658a0af1e9d6478cadcb4c745f4bd6751f97d8644786c0978b0"; };
"cacache@npm:15.3.0" = { filename = "cacache-npm-15.3.0-a7e5239c6a-a07327c27a.zip"; sha512 = "a07327c27a4152c04eb0a831c63c00390d90f94d51bb80624a66f4e14a6b6360bbf02a84421267bd4d00ca73ac9773287d8d7169e8d2eafe378d2ce140579db8"; };
"infer-owner@npm:1.0.4" = { filename = "infer-owner-npm-1.0.4-685ac3d2af-181e732764.zip"; sha512 = "181e732764e4a0611576466b4b87dac338972b839920b2a8cde43642e4ed6bd54dc1fb0b40874728f2a2df9a1b097b8ff83b56d5f8f8e3927f837fdcb47d8a89"; };
"promise-inflight@npm:1.0.1" = { filename = "promise-inflight-npm-1.0.1-5bb925afac-2274948309.zip"; sha512 = "22749483091d2c594261517f4f80e05226d4d5ecc1fc917e1886929da56e22b5718b7f2a75f3807e7a7d471bc3be2907fe92e6e8f373ddf5c64bae35b5af3981"; };
"p-map@npm:4.0.0" = { filename = "p-map-npm-4.0.0-4677ae07c7-cb0ab21ec0.zip"; sha512 = "cb0ab21ec0f32ddffd31dfc250e3afa61e103ef43d957cc45497afe37513634589316de4eb88abdfd969fe6410c22c0b93ab24328833b8eb1ccc087fc0442a1c"; };
"unique-filename@npm:1.1.1" = { filename = "unique-filename-npm-1.1.1-c885c5095b-cf4998c922.zip"; sha512 = "cf4998c9228cc7647ba7814e255dec51be43673903897b1786eff2ac2d670f54d4d733357eb08dea969aa5e6875d0e1bd391d668fbdb5a179744e7c7551a6f80"; };
"@npmcli/fs@npm:1.1.0" = { filename = "@npmcli-fs-npm-1.1.0-fa0ae1b053-e435b883b4.zip"; sha512 = "e435b883b4f8da8c95a820f458cabb7d86582406eed5ad79fc689000d3e2df17e1f475c4903627272c001357cabc70d8b4c62520cbdae8cfab1dfdd51949f408"; };
"@npmcli/move-file@npm:1.1.2" = { filename = "@npmcli-move-file-npm-1.1.2-4f6c7b3354-c96381d4a3.zip"; sha512 = "c96381d4a37448ea280951e46233f7e541058cf57a57d4094dd4bdcaae43fa5872b5f2eb6bfb004591a68e29c5877abe3cdc210cb3588cbf20ab2877f31a7de7"; };
"@gar/promisify@npm:1.1.2" = { filename = "@gar-promisify-npm-1.1.2-2343f94380-d05081e088.zip"; sha512 = "d05081e0887a49c178b75ee3067bd6ee086f73c154d121b854fb2e044e8a89cb1cbb6de3a0dd93a519b80f0531fda68b099dd7256205f7fbb3490324342f2217"; };
"unique-slug@npm:2.0.2" = { filename = "unique-slug-npm-2.0.2-f6ba1ddeb7-5b6876a645.zip"; sha512 = "5b6876a645da08d505dedb970d1571f6cebdf87044cb6b740c8dbb24f0d6e1dc8bdbf46825fd09f994d7cf50760e6f6e063cfa197d51c5902c00a861702eb75a"; };
"aggregate-error@npm:3.1.0" = { filename = "aggregate-error-npm-3.1.0-415a406f4e-1101a33f21.zip"; sha512 = "1101a33f21baa27a2fa8e04b698271e64616b886795fd43c31068c07533c7b3facfcaf4e9e0cab3624bd88f729a592f1c901a1a229c9e490eafce411a8644b79"; };
"imurmurhash@npm:0.1.4" = { filename = "imurmurhash-npm-0.1.4-610c5068a0-7cae75c8cd.zip"; sha512 = "7cae75c8cd9a50f57dadd77482359f659eaebac0319dd9368bcd1714f55e65badd6929ca58569da2b6494ef13fdd5598cd700b1eba23f8b79c5f19d195a3ecf7"; };
"clean-stack@npm:2.2.0" = { filename = "clean-stack-npm-2.2.0-a8ce435a5c-2ac8cd2b2f.zip"; sha512 = "2ac8cd2b2f5ec986a3c743935ec85b07bc174d5421a5efc8017e1f146a1cf5f781ae962618f416352103b32c9cd7e203276e8c28241bbe946160cab16149fb68"; };
"indent-string@npm:4.0.0" = { filename = "indent-string-npm-4.0.0-7b717435b2-824cfb9929.zip"; sha512 = "824cfb9929d031dabf059bebfe08cf3137365e112019086ed3dcff6a0a7b698cb80cf67ccccde0e25b9e2d7527aa6cc1fed1ac490c752162496caba3e6699612"; };
};
isolated."keccak@npm:3.0.2" = optionalOverride (args.overrideKeccakAttrs or null) (mkIsolatedBuild { pname = "keccak"; version = "3.0.2"; locators = [
"@gar/promisify@npm:1.1.2"
"@npmcli/fs@npm:1.1.0"
"@npmcli/move-file@npm:1.1.2"
"@tootallnate/once@npm:1.1.2"
"abbrev@npm:1.1.1"
"agent-base@npm:6.0.2"
"agentkeepalive@npm:4.2.0"
"aggregate-error@npm:3.1.0"
"ansi-regex@npm:5.0.1"
"aproba@npm:2.0.0"
"are-we-there-yet@npm:2.0.0"
"balanced-match@npm:1.0.2"
"brace-expansion@npm:1.1.11"
"cacache@npm:15.3.0"
"chownr@npm:2.0.0"
"clean-stack@npm:2.2.0"
"color-support@npm:1.1.3"
"concat-map@npm:0.0.1"
"console-control-strings@npm:1.1.0"
"debug@npm:4.3.3"
"delegates@npm:1.0.0"
"depd@npm:1.1.2"
"emoji-regex@npm:8.0.0"
"encoding@npm:0.1.13"
"env-paths@npm:2.2.1"
"err-code@npm:2.0.3"
"fs-minipass@npm:2.1.0"
"fs.realpath@npm:1.0.0"
"gauge@npm:4.0.0"
"glob@npm:7.2.0"
"graceful-fs@npm:4.2.9"
"has-unicode@npm:2.0.1"
"http-cache-semantics@npm:4.1.0"
"http-proxy-agent@npm:4.0.1"
"https-proxy-agent@npm:5.0.0"
"humanize-ms@npm:1.2.1"
"iconv-lite@npm:0.6.3"
"imurmurhash@npm:0.1.4"
"indent-string@npm:4.0.0"
"infer-owner@npm:1.0.4"
"inflight@npm:1.0.6"
"inherits@npm:2.0.4"
"ip@npm:1.1.5"
"is-fullwidth-code-point@npm:3.0.0"
"is-lambda@npm:1.0.1"
"isexe@npm:2.0.0"
"keccak@npm:3.0.2"
"lru-cache@npm:6.0.0"
"make-fetch-happen@npm:9.1.0"
"minimatch@npm:3.0.4"
"minipass-collect@npm:1.0.2"
"minipass-fetch@npm:1.4.1"
"minipass-flush@npm:1.0.5"
"minipass-pipeline@npm:1.2.4"
"minipass-sized@npm:1.0.3"
"minipass@npm:3.1.6"
"minizlib@npm:2.1.2"
"mkdirp@npm:1.0.4"
"ms@npm:2.1.2"
"ms@npm:2.1.3"
"negotiator@npm:0.6.2"
"node-addon-api@npm:2.0.2"
"node-gyp-build@npm:4.3.0"
"node-gyp@npm:8.4.1"
"nopt@npm:5.0.0"
"npmlog@npm:6.0.0"
"once@npm:1.4.0"
"p-map@npm:4.0.0"
"path-is-absolute@npm:1.0.1"
"promise-inflight@npm:1.0.1"
"promise-retry@npm:2.0.1"
"readable-stream@npm:3.6.0"
"retry@npm:0.12.0"
"rimraf@npm:3.0.2"
"safe-buffer@npm:5.2.1"
"safer-buffer@npm:2.1.2"
"semver@npm:7.3.5"
"set-blocking@npm:2.0.0"
"signal-exit@npm:3.0.6"
"smart-buffer@npm:4.2.0"
"socks-proxy-agent@npm:6.1.1"
"socks@npm:2.6.1"
"ssri@npm:8.0.1"
"string-width@npm:4.2.3"
"string_decoder@npm:1.3.0"
"strip-ansi@npm:6.0.1"
"tar@npm:6.1.11"
"unique-filename@npm:1.1.1"
"unique-slug@npm:2.0.2"
"util-deprecate@npm:1.0.2"
"which@npm:2.0.2"
"wide-align@npm:1.1.5"
"wrappy@npm:1.0.2"
"yallist@npm:4.0.0"
]; });
in optionalOverride overrideAttrs project
