# This file is generated by running "yarn install" inside your project.
# Manual changes might be lost - proceed with caution!

{ lib, nodejs, stdenv, fetchurl, writeText, writeShellScriptBin, git, cacert, gnused }:
{ src, symlinkPackages ? false, overrideAttrs ? null, netrcFilePath ? null, secretsEnvVars ? null, ... } @ args:

let

  yarnPath = ./.yarn/releases/yarn-3.1.1.cjs;
  yarnRelativePathString = "./.yarn/releases/yarn-3.1.1.cjs";
  yarnLock = ./yarn.lock;
  packageJson = ./package.json;
  yarnrcYaml = builtins.path {
    path = ./.yarnrc.yml;
    name = "yarnrc.yml";
  };
  yarnPlugins = builtins.path {
    path = ./.yarn/plugins;
    name = "yarnPlugins";
  };

  cacheFolder = ".yarn/cache";

  # Call overrideAttrs on a derivation if a function is provided.
  optionalOverride = fn: drv:
    if fn == null then drv else drv.overrideAttrs fn;

  # Common attributes between Yarn derivations.
  drvCommon = {
    # Make sure the build uses the right Node.js version everywhere.
    buildInputs = [ nodejs ];
    # Tell node-gyp to use the provided Node.js headers for native code builds.
    npm_config_nodedir = nodejs;
    # Tell node-pre-gyp to never fetch binaries / always build from source.
    npm_config_build_from_source = "true";
    # Defines the shell alias to run Yarn.
    postHook = ''
      yarn() {
        CI=1 node "${yarnPath}" "$@"
      }
    '';
  };

  setupProjectFiles = ''
    # package.json cannot be symlinked since when executing "yarn run ...", yarn
    # will follow the symlink and consider the location of the original file as
    # the projects root directory.
    cp ${packageJson} package.json
    ln -s ${yarnLock} yarn.lock
    ln -s ${yarnrcYaml} .yarnrc.yml

    mkdir -p .yarn
    ln -s ${yarnPlugins} .yarn/plugins

    mkdir -p $(dirname ${yarnRelativePathString})
    ln -s ${yarnPath} ${yarnRelativePathString}
  '';

  checkSandboxPathExists = writeShellScriptBin "check-sandbox-file-exists" ''
    set -ueo pipefail

    file_path=$1

    if ! test -e "$file_path"
    then
      echo >&2 "Error: $file_path does not exist or cannot be accessed due to permissions!"
      echo >&2 "  Make sure it's added to extra-sandbox-paths and that nixbld"
      echo >&2 "  user group has read access to it."
      exit 1
    fi
  '';

  linkNetrcFile = writeShellScriptBin "link-netrc-file" ''
    set -ueo pipefail

    netrc_file_path=$1
    home=$2

    ${checkSandboxPathExists}/bin/check-sandbox-file-exists "$netrc_file_path"

    if ! test -d "$home";
    then
      echo >&2 "given HOME path (''${home}) does not exist or is not a directory"
      exit 1
    fi

    echo >&2 "linking .netrc file at ''${netrc_file_path} to ''${home}"

    ln -s "$netrc_file_path" "$home"
  '';

  exportEnvVarsFromFilesIfAny = envVarNamesToPaths:
    if envVarNamesToPaths != null
    # build a list of export statement
    then lib.concatStringsSep "\n" (lib.mapAttrsToList
      (name: path: ''
        check-sandbox-file-exists "${path}"
        export ${name}=$(cat "${path}")
      '')
      envVarNamesToPaths
    )
    else ""
  ;

  # Create derivations for fetching dependencies.
  cacheDrvs = let
    builder = builtins.toFile "builder.sh" ''
      source $stdenv/setup

      ${exportEnvVarsFromFilesIfAny secretsEnvVars}

      home=$TMP

      ${
        if netrcFilePath != null
        then ''link-netrc-file "${netrcFilePath}" "$home"''
        else ""
      }

      build_dir=$TMP/build
      mkdir -p $build_dir
      cd $build_dir

      ${setupProjectFiles}

      mkdir -p ${cacheFolder}
      YARN_CACHE_FOLDER=$(pwd)/${cacheFolder}

      HOME="$home" \
        YARN_CACHE_FOLDER="$YARN_CACHE_FOLDER" \
        CI=1 \
        node '${yarnPath}' nixify fetch-one $locator

      # Because we change the cache dir, Yarn may generate a different name.
      output_filename_stripped=$(sed 's/-[^-]*\.[^-]*$//' <<< "$outputFilename")

      mv "$YARN_CACHE_FOLDER/$output_filename_stripped"-* $out
    '';
  in lib.mapAttrs (locator: { filename, sha512 }: stdenv.mkDerivation {
    inherit builder locator;
    # We need .zip extension since without pnp will not look inside the archive.
    name = lib.strings.sanitizeDerivationName locator + ".zip";
    buildInputs = [ nodejs ];
    nativeBuildInputs = [ git cacert linkNetrcFile checkSandboxPathExists ];
    outputFilename = filename;
    outputHashMode = "flat";
    outputHashAlgo = "sha512";
    outputHash = sha512;
  }) cacheEntries;

  # Create a shell snippet to copy dependencies from a list of derivations.
  mkCacheBuilderForDrvs = symlinkPackages: drvs:
    writeText "collect-cache.sh" (lib.concatMapStrings (drv: ''
      ${if symlinkPackages then "ln -s" else "cp"} ${drv} '${drv.outputFilename}'
    '') drvs);


  # Derivation with content of .yarn/cache and .pnp.cjs
  deps = stdenv.mkDerivation (drvCommon // {
    name = "yarn-3-test-deps";
    # Disable Nixify plugin to save on some unnecessary processing.
    yarn_enable_nixify = "false";

    configurePhase = ''
      output_dir=$out/libexec/deps
      mkdir -p $output_dir
      cd $output_dir

      ${setupProjectFiles}

      # Copy over the Yarn cache.
      mkdir -p ${cacheFolder}
      pushd '${cacheFolder}' > /dev/null
      source ${mkCacheBuilderForDrvs symlinkPackages (lib.attrValues cacheDrvs)}
      popd > /dev/null



      runHook postConfigure
    '';

    dontUnpack = true;
    dontBuild = true;

    installPhase = ''
      runHook preInstall

      # Yarn may need a writable home directory.
      export yarn_global_folder="$TMP"

      # Some node-gyp calls may call out to npm, which could fail due to an
      # read-only home dir.
      export HOME="$TMP"

      # running preConfigure after the cache is populated allows for
      # preConfigure to contain substituteInPlace for dependencies as well as the
      # main project. This is necessary for native bindings that maybe have
      # hardcoded values.
      runHook preConfigure

      # Run normal Yarn install to complete dependency installation.
      # YARN_VIRTUAL_FOLDER is set this way to make it easy to replace in
      # installPhase below, so that in the end virtual paths resolve to
      # packages in nix store.
      YARN_CACHE_FOLDER=$(pwd)/${cacheFolder} \
        yarn install --immutable --immutable-cache

      runHook postInstall
    '';

    passthru = {
      inherit nodejs;
    };
  });

  # Main project derivation.
  project = stdenv.mkDerivation (drvCommon // {
    inherit src;
    name = "yarn-3-test";

    nativeBuildInputs = [gnused];
    depsPath = "${deps}/libexec/deps";

    configurePhase = ''
      ${setupProjectFiles}
      # We can't symlink this one since it doesn't work as a symlink due to
      # packageLocations within it being relative path to this files locations
      # real location, therefore it needs to be located at the root of the
      # project for relative and workspace scoped imports to work.
      cp $depsPath/.pnp.cjs .pnp.cjs

      runHook postConfigure
    '';

    dontBuild = true;

    installPhase = ''
      runHook preInstall

      app_dir=$out/libexec/$name
      bin_dir=$out/bin

      mkdir -p $(dirname $app_dir) $out/bin

      # Move the entire project to the output directory.
      mv $PWD $app_dir
      cd $app_dir

      # sed helpers
      escape_sed_replacement () {
        echo "$1" | sed -e 's/[\/&]/\\&/g'
      }

      escape_sed_pattern () {
        echo "$1" | sed -e 's/[]\/$*.^[]/\\&/g'
      }

      # Replace packageLocation for the workspace and main package.
      sed_pattern='"packageLocation": "'$depsPath'/"'
      sed_replace='"packageLocation": "'$app_dir'/"'

      sed -E -i \
        -e "s/$(escape_sed_pattern "$sed_pattern")/$(escape_sed_replacement "$sed_replace")/g" \
        .pnp.cjs

      # Invoke a plugin internal command to setup binaries.
      yarn nixify install-bin $bin_dir

      runHook postInstall
    '';

    passthru = {
      inherit nodejs;
    };
  });

cacheEntries = {
"bitfinex-api-node@npm:4.0.16" = { filename = "bitfinex-api-node-npm-4.0.16-8aba213ffd-ae9741fdd9.zip"; sha512 = "ae9741fdd90102c5bdc52de6aefe9b49fc0fc9b1e18380d6887a3228cda25d60a16606afe13ba8535cb60f73658fb8b7bd21f8cb3db29c599c67d67bf288b2b5"; };
"bignumber.js@npm:9.0.2" = { filename = "bignumber.js-npm-9.0.2-583f690302-8637b71d0a.zip"; sha512 = "8637b71d0a99104b20413c47578953970006fec6b4df796b9dcfd9835ea9c402ea0e727eba9a5ca9f9a393c1d88b6168c5bbe0887598b708d4f8b4870ad62e1f"; };
"lodash.throttle@npm:4.1.1" = { filename = "lodash.throttle-npm-4.1.1-856641af92-129c0a28ce.zip"; sha512 = "129c0a28cee48b348aef146f638ef8a8b197944d4e9ec26c1890c19d9bf5a5690fe11b655c77a4551268819b32d27f4206343e30c78961f60b561b8608c8c805"; };
"cli-table3@npm:0.6.1" = { filename = "cli-table3-npm-0.6.1-310df32004-956e175f8e.zip"; sha512 = "956e175f8eb019c26465b9f1e51121c08d8978e2aab04be7f8520ea8a4e67906fcbd8516dfb77e386ae3730ef0281aa21a65613dffbfa3d62969263252bd25a9"; };
"cbq@npm:0.0.1" = { filename = "cbq-npm-0.0.1-f70cd4ebde-188236d404.zip"; sha512 = "188236d4044678bd8ba37e3f40eba2ebc735187ae02279230eb855ea06f1c088ec3f22b34a0de2f1b78a9471a40f9281acc5c5d9da88f006f65062c5defc6477"; };
"lodash@npm:4.17.21" = { filename = "lodash-npm-4.17.21-6382451519-eb835a2e51.zip"; sha512 = "eb835a2e51d381e561e508ce932ea50a8e5a68f4ebdd771ea240d3048244a8d13658acbd502cd4829768c56f2e16bdd4340b9ea141297d472517b83868e677f7"; };
"crc-32@npm:1.2.1" = { filename = "crc-32-npm-1.2.1-ac77b90365-b8942a4047.zip"; sha512 = "b8942a404766990b1ebbcc488fe5972afbabfea870362325165e26d1156abc3e987afb22cc74bd624a1570d8837d7b910534e83a8ffb9413e6ff02ec5cc638aa"; };
"debug@npm:4.3.3" = { filename = "debug-npm-4.3.3-710fd4cc7f-14472d56fe.zip"; sha512 = "14472d56fe4a94dbcfaa6dbed2dd3849f1d72ba78104a1a328047bb564643ca49df0224c3a17fa63533fd11dd3d4c8636cd861191232a2c6735af00cc2d4de16"; };
"request@npm:2.88.2" = { filename = "request-npm-2.88.2-f4a57c72c4-4e112c087f.zip"; sha512 = "4e112c087f6eabe7327869da2417e9d28fcd0910419edd2eb17b6acfc4bfa1dad61954525949c228705805882d8a98a86a0ea12d7f739c01ee92af7062996983"; };
"exit-on-epipe@npm:1.0.1" = { filename = "exit-on-epipe-npm-1.0.1-1aade96e24-e8ab494041.zip"; sha512 = "e8ab4940416d19f311b3c9226e3725c6c4c6026fe682266ecc0ff33a455d585fe3e4ee757857c7bf1d0491b478cb232b8e395dfb438e65ac87317eda47304c32"; };
"colors@npm:1.4.0" = { filename = "colors-npm-1.4.0-7e2cf12234-98aa2c2418.zip"; sha512 = "98aa2c2418ad87dedf25d781be69dc5fc5908e279d9d30c34d8b702e586a0474605b3a189511482b9d5ed0d20c867515d22749537f7bc546256c6014f3ebdcec"; };
"string-width@npm:4.2.3" = { filename = "string-width-npm-4.2.3-2c27177bae-e52c10dc3f.zip"; sha512 = "e52c10dc3fbfcd6c3a15f159f54a90024241d0f149cf8aed2982a2d801d2e64df0bf1dc351cf8e95c3319323f9f220c16e740b06faecd53e2462df1d2b5443fb"; };
"printj@npm:1.3.1" = { filename = "printj-npm-1.3.1-5df08ba24a-3bb8976e02.zip"; sha512 = "3bb8976e02c2a5943f86bf7d1cbe7764fa9fb6fb177cbc9fe0044adbd7be11dbf82e4c72d381f4d2ddc578fada92ea24ab263069549254cb796a252f11fd1ddf"; };
"bluebird@npm:3.7.2" = { filename = "bluebird-npm-3.7.2-6a54136ee3-869417503c.zip"; sha512 = "869417503c722e7dc54ca46715f70e15f4d9c602a423a02c825570862d12935be59ed9c7ba34a9b31f186c017c23cac6b54e35446f8353059c101da73eac22ef"; };
"ms@npm:2.1.2" = { filename = "ms-npm-2.1.2-ec0c1512ff-673cdb2c31.zip"; sha512 = "673cdb2c3133eb050c745908d8ce632ed2c02d85640e2edb3ace856a2266a813b30c613569bf3354fdf4ea7d1a1494add3bfa95e2713baa27d0c2c71fc44f58f"; };
"aws-sign2@npm:0.7.0" = { filename = "aws-sign2-npm-0.7.0-656c6cb84d-b148b0bb07.zip"; sha512 = "b148b0bb0778098ad8cf7e5fc619768bcb51236707ca1d3e5b49e41b171166d8be9fdc2ea2ae43d7decf02989d0aaa3a9c4caa6f320af95d684de9b548a71525"; };
"extend@npm:3.0.2" = { filename = "extend-npm-3.0.2-e1ca07ac54-a50a8309ca.zip"; sha512 = "a50a8309ca65ea5d426382ff09f33586527882cf532931cb08ca786ea3146c0553310bda688710ff61d7668eba9f96b923fe1420cdf56a2c3eaf30fcab87b515"; };
"is-fullwidth-code-point@npm:3.0.0" = { filename = "is-fullwidth-code-point-npm-3.0.0-1ecf4ebee5-44a30c2945.zip"; sha512 = "44a30c29457c7fb8f00297bce733f0a64cd22eca270f83e58c105e0d015e45c019491a4ab2faef91ab51d4738c670daff901c799f6a700e27f7314029e99e348"; };
"combined-stream@npm:1.0.8" = { filename = "combined-stream-npm-1.0.8-dc14d4a63a-49fa4aeb49.zip"; sha512 = "49fa4aeb4916567e33ea81d088f6584749fc90c7abec76fd516bf1c5aa5c79f3584b5ba3de6b86d26ddd64bae5329c4c7479343250cfe71c75bb366eae53bb7c"; };
"http-signature@npm:1.2.0" = { filename = "http-signature-npm-1.2.0-ee92426f34-3324598712.zip"; sha512 = "3324598712266a9683585bb84a75dec4fd550567d5e0dd4a0fff6ff3f74348793404d3eeac4918fa0902c810eeee1a86419e4a2e92a164132dfe6b26743fb47c"; };
"strip-ansi@npm:6.0.1" = { filename = "strip-ansi-npm-6.0.1-caddc7cb40-f3cd25890a.zip"; sha512 = "f3cd25890aef3ba6e1a74e20896c21a46f482e93df4a06567cebf2b57edabb15133f1f94e57434e0a958d61186087b1008e89c94875d019910a213181a14fc8c"; };
"har-validator@npm:5.1.5" = { filename = "har-validator-npm-5.1.5-bd9ac162f5-b998a7269c.zip"; sha512 = "b998a7269ca560d7f219eedc53e2c664cd87d487e428ae854a6af4573fc94f182fe9d2e3b92ab968249baec7ebaf9ead69cf975c931dc2ab282ec182ee988280"; };
"forever-agent@npm:0.6.1" = { filename = "forever-agent-npm-0.6.1-01dae53bf9-766ae6e220.zip"; sha512 = "766ae6e220f5fe23676bb4c6a99387cec5b7b62ceb99e10923376e27bfea72f3c3aeec2ba5f45f3f7ba65d6616965aa7c20b15002b6860833bb6e394dea546a8"; };
"emoji-regex@npm:8.0.0" = { filename = "emoji-regex-npm-8.0.0-213764015c-d4c5c39d5a.zip"; sha512 = "d4c5c39d5a9868b5fa152f00cada8a936868fd3367f33f71be515ecee4c803132d11b31a6222b2571b1e5f7e13890156a94880345594d0ce7e3c9895f560f192"; };
"form-data@npm:2.3.3" = { filename = "form-data-npm-2.3.3-c016cc11c0-10c1780fa1.zip"; sha512 = "10c1780fa13dbe1ff3100114c2ce1f9307f8be10b14bf16e103815356ff567b6be39d70fc4a40f8990b9660012dc24b0f5e1dde1b6426166eb23a445ba068ca3"; };
"json-stringify-safe@npm:5.0.1" = { filename = "json-stringify-safe-npm-5.0.1-064ddd6ab4-48ec0adad5.zip"; sha512 = "48ec0adad5280b8a96bb93f4563aa1667fd7a36334f79149abd42446d0989f2ddc58274b479f4819f1f00617957e6344c886c55d05a4e15ebb4ab931e4a6a8ee"; };
"caseless@npm:0.12.0" = { filename = "caseless-npm-0.12.0-e83bc5df83-b43bd4c440.zip"; sha512 = "b43bd4c440aa1e8ee6baefee8063b4850fd0d7b378f6aabc796c9ec8cb26d27fb30b46885350777d9bd079c5256c0e1329ad0dc7c2817e0bb466810ebb353751"; };
"mime-types@npm:2.1.34" = { filename = "mime-types-npm-2.1.34-3cd0bb907c-67013de9e9.zip"; sha512 = "67013de9e9d6799bde6d669d18785b7e18bcd212e710d3e04a4727f92f67a8ad4e74aee24be28b685adb794944814bde649119b58ee3282ffdbee58f9278d9f3"; };
"delayed-stream@npm:1.0.0" = { filename = "delayed-stream-npm-1.0.0-c5a4c4cc02-46fe6e83e2.zip"; sha512 = "46fe6e83e2cb1d85ba50bd52803c68be9bd953282fa7096f51fc29edd5d67ff84ff753c51966061e5ba7cb5e47ef6d36a91924eddb7f3f3483b1c560f77a0020"; };
"uuid@npm:3.4.0" = { filename = "uuid-npm-3.4.0-4fd8ef88ad-58de2feed6.zip"; sha512 = "58de2feed61c59060b40f8203c0e4ed7fd6f99d42534a499f1741218a1dd0c129f4aa1de797bcf822c8ea5da7e4137aa3673431a96dae729047f7aca7b27866f"; };
"tunnel-agent@npm:0.6.0" = { filename = "tunnel-agent-npm-0.6.0-64345ab7eb-05f6510358.zip"; sha512 = "05f6510358f8afc62a057b8b692f05d70c1782b70db86d6a1e0d5e28a32389e52fa6e7707b6c5ecccacc031462e4bc35af85ecfe4bbc341767917b7cf6965711"; };
"is-typedarray@npm:1.0.0" = { filename = "is-typedarray-npm-1.0.0-bbd99de5b6-3508c6cd0a.zip"; sha512 = "3508c6cd0a9ee2e0df2fa2e9baabcdc89e911c7bd5cf64604586697212feec525aa21050e48affb5ffc3df20f0f5d2e2cf79b08caa64e1ccc9578e251763aef7"; };
"jsprim@npm:1.4.2" = { filename = "jsprim-npm-1.4.2-1ae6cade9a-2ad1b9fdcc.zip"; sha512 = "2ad1b9fdcccae8b3d580fa6ced25de930eaa1ad154db21bbf8478a4d30bbbec7925b5f5ff29b933fba9412b16a17bd484a8da4fdb3663b5e27af95dd693bab2a"; };
"safe-buffer@npm:5.2.1" = { filename = "safe-buffer-npm-5.2.1-3481c8aa9b-b99c4b41fd.zip"; sha512 = "b99c4b41fdd67a6aaf280fcd05e9ffb0813654894223afb78a31f14a19ad220bba8aba1cb14eddce1fcfb037155fe6de4e861784eb434f7d11ed58d1e70dd491"; };
"isstream@npm:0.1.2" = { filename = "isstream-npm-0.1.2-8581c75385-1eb2fe63a7.zip"; sha512 = "1eb2fe63a729f7bdd8a559ab552c69055f4f48eb5c2f03724430587c6f450783c8f1cd936c1c952d0a927925180fcc892ebd5b174236cf1065d4bd5bdb37e963"; };
"ansi-regex@npm:5.0.1" = { filename = "ansi-regex-npm-5.0.1-c963a48615-2aa4bb54ca.zip"; sha512 = "2aa4bb54caf2d622f1afdad09441695af2a83aa3fe8b8afa581d205e57ed4261c183c4d3877cee25794443fde5876417d859c108078ab788d6af7e4fe52eb66b"; };
"sshpk@npm:1.17.0" = { filename = "sshpk-npm-1.17.0-95f17f597f-ba109f65c8.zip"; sha512 = "ba109f65c8e6c35133b8e6ed5576abeff8aa8d614824b7275ec3ca308f081fef483607c28d97780c1e235818b0f93ed8c8b56d0a5968d5a23fd6af57718c7597"; };
"qs@npm:6.5.3" = { filename = "qs-npm-6.5.3-90b2635484-6f20bf08ca.zip"; sha512 = "6f20bf08cabd90c458e50855559539a28d00b2f2e7dddcb66082b16a43188418cb3cb77cbd09268bcef6022935650f0534357b8af9eeb29bf0f27ccb17655692"; };
"blessed-contrib@npm:4.10.1" = { filename = "blessed-contrib-npm-4.10.1-c154f63087-26e6c72c30.zip"; sha512 = "26e6c72c30852d91eb4bbcebadfd26a543d987781ec26ef365f4dd8a2a55b120f72e3e477941af83b471d6ca5e2c373371f49ca5f76902d053e7b3f3923e5023"; };
"strip-ansi@npm:3.0.1" = { filename = "strip-ansi-npm-3.0.1-6aec1365b9-9b974de611.zip"; sha512 = "9b974de611ce5075c70629c00fa98c46144043db92ae17748fb780f706f7a789e9989fd10597b7c2053ae8d1513fd707816a91f1879b2f71e6ac0b6a863db465"; };
"ansi-regex@npm:2.1.1" = { filename = "ansi-regex-npm-2.1.1-ddd24d102b-190abd03e4.zip"; sha512 = "190abd03e4ff86794f338a31795d262c1dfe8c91f7e01d04f13f646f1dcb16c5800818f886047876f1272f065570ab86b24b99089f8b68a0e11ff19aed4ca8f1"; };
"oauth-sign@npm:0.9.0" = { filename = "oauth-sign-npm-0.9.0-7aa9422221-8f5497a127.zip"; sha512 = "8f5497a127967866a3c67094c21efd295e46013a94e6e828573c62220e9af568cc1d2d04b16865ba583e430510fa168baf821ea78f355146d8ed7e350fc44c64"; };
"har-schema@npm:2.0.0" = { filename = "har-schema-npm-2.0.0-3a318c0ca5-d8946348f3.zip"; sha512 = "d8946348f333fb09e2bf24cc4c67eabb47c8e1d1aa1c14184c7ffec1140a49ec8aa78aa93677ae452d71d5fc0fdeec20f0c8c1237291fc2bcb3f502a5d204f9b"; };
"mime-db@npm:1.51.0" = { filename = "mime-db-npm-1.51.0-d5e42b45ad-613b1ac9d6.zip"; sha512 = "613b1ac9d6e725cc24444600b124a7f1ce6c60b1baa654f39a3e260d0995a6dffc5693190217e271af7e2a5612dae19f2a73f3e316707d797a7391165f7ef423"; };
"verror@npm:1.10.0" = { filename = "verror-npm-1.10.0-c3f839c579-c431df0bed.zip"; sha512 = "c431df0bedf2088b227a4e051e0ff4ca54df2c114096b0c01e1cbaadb021c30a04d7dd5b41ab277bcd51246ca135bf931d4c4c796ecae7a4fef6d744ecef36ea"; };
"safer-buffer@npm:2.1.2" = { filename = "safer-buffer-npm-2.1.2-8d5c0b705e-cab8f25ae6.zip"; sha512 = "cab8f25ae6f1434abee8d80023d7e72b598cf1327164ddab31003c51215526801e40b66c5e65d658a0af1e9d6478cadcb4c745f4bd6751f97d8644786c0978b0"; };
"ajv@npm:6.12.6" = { filename = "ajv-npm-6.12.6-4b5105e2b2-874972efe5.zip"; sha512 = "874972efe5c4202ab0a68379481fbd3d1b5d0a7bd6d3cc21d40d3536ebff3352a2a1fabb632d4fd2cc7fe4cbdcd5ed6782084c9bbf7f32a1536d18f9da5007d4"; };
"json-schema@npm:0.4.0" = { filename = "json-schema-npm-0.4.0-e776313070-66389434c3.zip"; sha512 = "66389434c3469e698da0df2e7ac5a3281bcff75e797a5c127db7c5b56270e01ae13d9afa3c03344f76e32e81678337a8c912bdbb75101c62e487dc3778461d72"; };
"bcrypt-pbkdf@npm:1.0.2" = { filename = "bcrypt-pbkdf-npm-1.0.2-80db8b16ed-4edfc9fe7d.zip"; sha512 = "4edfc9fe7d07019609ccf797a2af28351736e9d012c8402a07120c4453a3b789a15f2ee1530dc49eee8f7eb9379331a8dd4b3766042b9e502f74a68e7f662291"; };
"ecc-jsbn@npm:0.1.2" = { filename = "ecc-jsbn-npm-0.1.2-85b7a7be89-22fef4b620.zip"; sha512 = "22fef4b6203e5f31d425f5b711eb389e4c6c2723402e389af394f8411b76a488fa414d309d866e2b577ce3e8462d344205545c88a8143cc21752a5172818888a"; };
"jsbn@npm:0.1.1" = { filename = "jsbn-npm-0.1.1-0eb7132404-e5ff29c1b8.zip"; sha512 = "e5ff29c1b8d965017ef3f9c219dacd6e40ad355c664e277d31246c90545a02e6047018c16c60a00f36d561b3647215c41894f5d869ada6908a2e0ce4200c88f2"; };
"dashdash@npm:1.14.1" = { filename = "dashdash-npm-1.14.1-be8f10a286-3634c24957.zip"; sha512 = "3634c249570f7f34e3d34f866c93f866c5b417f0dd616275decae08147dcdf8fccfaa5947380ccfb0473998ea3a8057c0b4cd90c875740ee685d0624b2983598"; };
"tweetnacl@npm:0.14.5" = { filename = "tweetnacl-npm-0.14.5-a3f766c0d1-6061daba17.zip"; sha512 = "6061daba1724f59473d99a7bb82e13f211cdf6e31315510ae9656fefd4779851cb927adad90f3b488c8ed77c106adc0421ea8055f6f976ff21b27c5c4e918487"; };
"chalk@npm:1.1.3" = { filename = "chalk-npm-1.1.3-59144c3a87-9d2ea6b98f.zip"; sha512 = "9d2ea6b98fc2b7878829eec223abcf404622db6c48396a9b9257f6d0ead2acf18231ae368d6a664a83f272b0679158da12e97b5229f794939e555cc574478acd"; };
"fast-deep-equal@npm:3.1.3" = { filename = "fast-deep-equal-npm-3.1.3-790edcfcf5-e21a9d8d84.zip"; sha512 = "e21a9d8d84f53493b6aa15efc9cfd53dd5b714a1f23f67fb5dc8f574af80df889b3bce25dc081887c6d25457cce704e636395333abad896ccdec03abaf1f3f9d"; };
"uri-js@npm:4.4.1" = { filename = "uri-js-npm-4.4.1-66d11cbcaf-7167432de6.zip"; sha512 = "7167432de6817fe8e9e0c9684f1d2de2bb688c94388f7569f7dbdb1587c9f4ca2a77962f134ec90be0cc4d004c939ff0d05acc9f34a0db39a3c797dada262633"; };
"fast-json-stable-stringify@npm:2.1.0" = { filename = "fast-json-stable-stringify-npm-2.1.0-02e8905fda-b191531e36.zip"; sha512 = "b191531e36c607977e5b1c47811158733c34ccb3bfde92c44798929e9b4154884378536d26ad90dfecd32e1ffc09c545d23535ad91b3161a27ddbb8ebe0cbecb"; };
"core-util-is@npm:1.0.2" = { filename = "core-util-is-npm-1.0.2-9fc2b94dc3-7a4c925b49.zip"; sha512 = "7a4c925b497a2c91421e25bf76d6d8190f0b2359a9200dbeed136e63b2931d6294d3b1893eda378883ed363cd950f44a12a401384c609839ea616befb7927dab"; };
"json-schema-traverse@npm:0.4.1" = { filename = "json-schema-traverse-npm-0.4.1-4759091693-7486074d3b.zip"; sha512 = "7486074d3ba247769fda17d5181b345c9fb7d12e0da98b22d1d71a5db9698d8b4bd900a3ec1a4ffdd60846fc2556274a5c894d0c48795f14cb03aeae7b55260b"; };
"ansi-styles@npm:2.2.1" = { filename = "ansi-styles-npm-2.2.1-f3297e782c-ebc0e00381.zip"; sha512 = "ebc0e00381f2a29000d1dac8466a640ce11943cef3bda3cd0020dc042e31e1058ab59bf6169cd794a54c3a7338a61ebc404b7c91e004092dd20e028c432c9c2c"; };
"supports-color@npm:2.0.0" = { filename = "supports-color-npm-2.0.0-22c0f0adbc-602538c581.zip"; sha512 = "602538c5812b9006404370b5a4b885d3e2a1f6567d314f8b4a41974ffe7d08e525bf92ae0f9c7030e3b4c78e4e34ace55d6a67a74f1571bc205959f5972f88f0"; };
"sparkline@npm:0.1.2" = { filename = "sparkline-npm-0.1.2-1de52843d3-7fab1c94ca.zip"; sha512 = "7fab1c94ca2aaa036aa213784df6431a5876cfe5eb9f3442407bc0086aa9e146e89437c39c530d7c408fc0c368b294c135d8c884a716039b53bbb617917f876c"; };
"has-ansi@npm:2.0.0" = { filename = "has-ansi-npm-2.0.0-9bf0cff2af-1b51daa021.zip"; sha512 = "1b51daa0214440db171ff359d0a2d17bc20061164c57e76234f614c91dbd2a79ddd68dfc8ee73629366f7be45a6df5f2ea9de83f52e1ca24433f2cc78c35d8ec"; };
"x256@npm:0.0.2" = { filename = "x256-npm-0.0.2-fc25a23ccb-891a67c4f9.zip"; sha512 = "891a67c4f946f6aa95902e8ebbdafd54ab8fb5851b96fb7b303206a0400cad9e8ea4bc920ef91e98ec7e3af9c1cd8cc6fa205f9a0f0f4e619dcd82f1c1e38447"; };
"picture-tuber@npm:1.0.2" = { filename = "picture-tuber-npm-1.0.2-bb959ae3db-309138d032.zip"; sha512 = "309138d032b3f638af27091a526507ad725c64fc2cab3033dca1b9cb0f0ee7c89de3691ebb77198cc70f9b785990d7cb649db06bcd1d9c275861869c6d9b3fea"; };
"nopt@npm:2.1.2" = { filename = "nopt-npm-2.1.2-cf46bcd68a-eb7bf965c0.zip"; sha512 = "eb7bf965c0117d537f1859b5da1d33cf3d48c63fa4c7f95ed1356fa07323ea5938878cf6bd511b7c6240c21a3b3f079066398c1d26dd9e2eb6235d0963013b7f"; };
"event-stream@npm:0.9.8" = { filename = "event-stream-npm-0.9.8-92d829b0de-526b7f0365.zip"; sha512 = "526b7f0365377727357b03b677a55a7177c1a2138121b293d0b864889a67f470d8317d6979993b1a0c79ace1a24b453d0a5763f60c528768bb2437b6010be229"; };
"abbrev@npm:1.1.1" = { filename = "abbrev-npm-1.1.1-3659247eab-a4a97ec07d.zip"; sha512 = "a4a97ec07d7ea112c517036882b2ac22f3109b7b19077dc656316d07d308438aac28e4d9746dc4d84bf6b1e75b4a7b0a5f3cb30592419f128ca9a8cee3bcfa17"; };
"png-js@npm:0.1.1" = { filename = "png-js-npm-0.1.1-f49e26e7fa-755d025d5e.zip"; sha512 = "755d025d5e0f02f82f07627a6bcf9c7d2bcdaeb5aa8372953a9cb515a84883b664439931ec1e397eb7d696920cc6c9e70afcedf90d3e889cd9163afab64c71f4"; };
"optimist@npm:0.3.7" = { filename = "optimist-npm-0.3.7-f279d1b7a7-adc02acb8b.zip"; sha512 = "adc02acb8b76d242e56714b47c8c96916b25a5ac2da7b9f735e1f946a970f266f71d53eff0b61d9582ef948301e94734f03b784fa7c309aed0fe7db403d22046"; };
"optimist@npm:0.2.8" = { filename = "optimist-npm-0.2.8-21c69b0b58-e43cbf95b9.zip"; sha512 = "e43cbf95b9005f38bc6a47eeede5cecbac0617cb15405ca29aa79891d1ef31053936e8b596eaf0e0d5d40c24a57ea810c06b82daddcd3f949311ef4699e62eb3"; };
"wordwrap@npm:0.0.3" = { filename = "wordwrap-npm-0.0.3-ab90803074-dfc2d3512e.zip"; sha512 = "dfc2d3512e857ae4b3bc2e8d4e5d2c285c28a4b87cd1d81c977ce9a1a99152d355807e046851a3d61148f39d877fbb889352e07b65a9cbdd2256aa928e159026"; };
"punycode@npm:2.1.1" = { filename = "punycode-npm-2.1.1-26eb3e15cf-823bf443c6.zip"; sha512 = "823bf443c6dd14f669984dea25757b37993f67e8d94698996064035edd43bed8a5a17a9f12e439c2b35df1078c6bec05a6c86e336209eb1061e8025c481168e8"; };
"readline-promise@npm:1.0.5" = { filename = "readline-promise-npm-1.0.5-c4a490ad5b-dd71cc24f6.zip"; sha512 = "dd71cc24f69335fb4771fba82b9137ba8048df6392bc9a10354e31c4970c63e6dd1627e09435e37f9b046b95363e458822f3e3482ba41d7a693fa0c13a3975e2"; };
"bfx-api-node-util@npm:1.0.11" = { filename = "bfx-api-node-util-npm-1.0.11-bb0f8fc5d7-131ee276a5.zip"; sha512 = "131ee276a5f92b9139d48a5e32cc35dde352e9a87220fcc4d6cfbea37df6b0e4d721560b1d0883997d539e4a6d7deeb5d85dbe1731239f57487aebd84a09c762"; };
"bignumber.js@npm:9.0.0" = { filename = "bignumber.js-npm-9.0.0-ce190bcd7c-51f37890bc.zip"; sha512 = "51f37890bca58bded63720add832b1c4898cf5b8ad95b5d4d9c3e763c461163d0355d11d91b740b0216b02e4e8cbb02455b28ee32140b775d96a39bbd817fdf6"; };
"blessed@npm:0.1.81" = { filename = "blessed-npm-0.1.81-7da02fe8f4-a8f96978cc.zip"; sha512 = "a8f96978cc8e3e5ac887c43df8523074ba4352b9a055d8b078c60ae1f9f62837c9eb620e5fc78ccbb005119167234fcf788915a16428c1c397a7fbf9f630b42c"; };
"copy@npm:0.3.2" = { filename = "copy-npm-0.3.2-7b773f1a5a-e4a9d90b13.zip"; sha512 = "e4a9d90b132f216ea78f2c39123ffd051c9c40da5b75446ba4eb1b6263bb2379dbf5153f4c579069ef262477647242b718a6ab778eee575d62a36ac48e15fe90"; };
"bfx-api-node-ws1@npm:1.0.4" = { filename = "bfx-api-node-ws1-npm-1.0.4-6eb259fe88-c795a2f312.zip"; sha512 = "c795a2f31214e93f2326aaf7ddc2427d65ab92975cafedd58f9bdf7b920c3a91ca3ead722d2ce17d13da62369e0120864239f6c4813a6100eff5bee003264f24"; };
"bluebird@npm:3.5.5" = { filename = "bluebird-npm-3.5.5-2719a585f8-2e53b556a3.zip"; sha512 = "2e53b556a34e38999c5075b6fcec6aa46b2fb9ac2e6e60c406da6c677fb04f64cb2d7c9d0daacebe6a8afc99e65511b49df97d4a65dcb087804659f3b6a70d00"; };
"debug@npm:4.1.1" = { filename = "debug-npm-4.1.1-540248b3aa-1e681f5cce.zip"; sha512 = "1e681f5cce94ba10f8dde74b20b42e4d8cf0d2a6700f4c165bb3bb6885565ef5ca5885bf07e704974a835f2415ff095a63164f539988a1f07e8a69fe8b1d65ad"; };
"ms@npm:2.1.3" = { filename = "ms-npm-2.1.3-81ff3cfac1-aa92de6080.zip"; sha512 = "aa92de608021b242401676e35cfa5aa42dd70cbdc082b916da7fb925c542173e36bce97ea3e804923fe92c0ad991434e4a38327e15a1b5b5f945d66df615ae6d"; };
"lossless-json@npm:1.0.5" = { filename = "lossless-json-npm-1.0.5-3592be347b-c26a231aaa.zip"; sha512 = "c26a231aaaa334dda42ef74ccf01a8558d15de815fd72fd3e47c549da11e3f47ae8f57c5ea26a298473844f889d1645a8b7835d507db430887dd598e9b0a6648"; };
"p-iteration@npm:1.1.8" = { filename = "p-iteration-npm-1.1.8-550aacc1f2-3eb8d8affc.zip"; sha512 = "3eb8d8affc2ef947c076807e5c57030949abad0ff81759ebc54fc43823e30ce918e69b035bf1884991c61b7885c77efaf32c0de7ac01110a2c874f6aa81e0d7f"; };
"bfx-api-node-rest@npm:3.1.0" = { filename = "bfx-api-node-rest-npm-3.1.0-4adb544724-d7ae3d5efc.zip"; sha512 = "d7ae3d5efcac738f6eef41e2087e863b3355b2846245ba032f94f967c98dd2d1cb23ae5e19d403b14e8223f45fa7208acf1bee592cd61834ae97c6993f9154a2"; };
"request-promise@npm:4.2.6" = { filename = "request-promise-npm-4.2.6-37010e90c3-1856c718cb.zip"; sha512 = "1856c718cb4b888db8b6a206537ecac47390ea4fbdaef00da9a6169a03dd66a95c38493713f927f78a19bfeb28dcb28f5d20f6ab927d644d9e0626847d808f9f"; };
"extend-shallow@npm:2.0.1" = { filename = "extend-shallow-npm-2.0.1-e6ef52b29c-8fb58d9d7a.zip"; sha512 = "8fb58d9d7a511f4baf78d383e637bd7d2e80843bd9cd0853649108ea835208fb614da502a553acc30208e1325240bb7cc4a68473021612496bb89725483656d8"; };
"async-each@npm:1.0.3" = { filename = "async-each-npm-1.0.3-464af5d2f3-868651cfeb.zip"; sha512 = "868651cfeb209970b367fbb96df1e1c8dc0b22c681cda7238417005ab2a5fbd944ee524b43f2692977259a57b7cc2547e03ff68f2b5113dbdf953d48cc078dc3"; };
"ws@npm:7.5.6" = { filename = "ws-npm-7.5.6-957f210696-0c2ffc9a53.zip"; sha512 = "0c2ffc9a539dd61dd2b00ff6cc5c98a3371e2521011fe23da4b3578bb7ac26cbdf7ca8a68e8e08023c122ae247013216dde2a20c908de415a6bcc87bdef68c87"; };
"ws@npm:3.0.0" = { filename = "ws-npm-3.0.0-8a2c2ad888-31892d832f.zip"; sha512 = "31892d832f9ab68425dccd900c98ae5cce3a0a98721f93fc2af4a1fcf21411935277cfdb21afdf954122f93098d58d89a6f9cb9eeecfef27f56bd804c409ebf8"; };
"safe-buffer@npm:5.0.1" = { filename = "safe-buffer-npm-5.0.1-7d6c7984a2-640f78a802.zip"; sha512 = "640f78a802831d8ea6cb60943b8f171854659908b62272acb32d15b5e51583f788e3edaf5827edd6883041432364094e6e551bd0eb6b68f0ac7af7e5a01f9e35"; };
"log-ok@npm:0.1.1" = { filename = "log-ok-npm-0.1.1-112d4caa91-69784f6fb5.zip"; sha512 = "69784f6fb56225639476860037ddf0134df731785d05a2b19bac8610f73100b1e1d924e51b310fe21b175edae40afd1fe565dab2c1348bd88bfc96d4e66b29ed"; };
"has-glob@npm:0.1.1" = { filename = "has-glob-npm-0.1.1-f2eed5a9f0-96bf0cb2a6.zip"; sha512 = "96bf0cb2a6a3339ba0ff721d3b6b2c6c394b729f51a79ee9aec4909f97bd1e763f8f9384dfde4c9931b4dbbfe5d3bb8db29e541906dba329fb299f5321a3dbaa"; };
"glob-parent@npm:2.0.0" = { filename = "glob-parent-npm-2.0.0-43401abb76-734fc461d9.zip"; sha512 = "734fc461d9d2753dd490dd072df6ce41fe4ebb60e9319b108bc538707b21780af3a61c3961ec2264131fad5d3d9a493e013a775aef11a69ac2f49fd7d8f46457"; };
"graceful-fs@npm:4.2.9" = { filename = "graceful-fs-npm-4.2.9-ee48e00aaa-68ea4e07ff.zip"; sha512 = "68ea4e07ff2c041ada184f9278b830375f8e0b75154e3f080af6b70f66172fabb4108d19b3863a96b53fc068a310b9b6493d86d1291acc5f3861eb4b79d26ad6"; };
"mkdirp@npm:0.5.5" = { filename = "mkdirp-npm-0.5.5-6bc76534fc-3bce20ea52.zip"; sha512 = "3bce20ea525f9477befe458ab85284b0b66c8dc3812f94155af07c827175948cdd8114852ac6c6d82009b13c1048c37f6d98743eb019651ee25c39acc8aabe7d"; };
"matched@npm:0.4.4" = { filename = "matched-npm-0.4.4-f83226201d-d961f00558.zip"; sha512 = "d961f00558c41aa6becdbe67f82e7c40f7cf0bbdc10d78ffe0c42461b07af29c24b2307ee4c1bd19f77d80318cb186f8b9f95c5953814683df6fe9af0fc5b90a"; };
"performance-now@npm:2.1.0" = { filename = "performance-now-npm-2.1.0-45e3ce7e49-534e641aa8.zip"; sha512 = "534e641aa8f7cba160f0afec0599b6cecefbb516a2e837b512be0adbe6c1da5550e89c78059c7fabc5c9ffdf6627edabe23eb7c518c4500067a898fa65c2b550"; };
"tough-cookie@npm:2.5.0" = { filename = "tough-cookie-npm-2.5.0-79a2fe43fe-16a8cd0902.zip"; sha512 = "16a8cd090224dd176eee23837cbe7573ca0fa297d7e468ab5e1c02d49a4e9a97bb05fef11320605eac516f91d54c57838a25864e8680e27b069a5231d8264977"; };
"aws4@npm:1.11.0" = { filename = "aws4-npm-1.11.0-283476ad94-5a00d045fd.zip"; sha512 = "5a00d045fd0385926d20ebebcfba5ec79d4482fe706f63c27b324d489a04c68edb0db99ed991e19eda09cb8c97dc2452059a34d97545cebf591d7a2b5a10999f"; };
"is-extendable@npm:0.1.1" = { filename = "is-extendable-npm-0.1.1-322b4649ec-3875571d20.zip"; sha512 = "3875571d20a7563772ecc7a5f36cb03167e9be31ad259041b4a8f73f33f885441f778cee1f1fe0085eb4bc71679b9d8c923690003a36a6a5fdf8023e6e3f0672"; };
"ansi-green@npm:0.1.1" = { filename = "ansi-green-npm-0.1.1-3c2d3713f9-9e256207a0.zip"; sha512 = "9e256207a06628fa51c4e6b6dfa088a032cc7b98c34735af078ecf967cae90a2bc946671abc9b6a97e45f442538ee01e25a29e5556f4b4d6bb981ab734cce9ea"; };
"stealthy-require@npm:1.1.1" = { filename = "stealthy-require-npm-1.1.1-0105ec8207-6805b857a9.zip"; sha512 = "6805b857a9f3a6a1079fc6652278038b81011f2a5b22cbd559f71a6c02087e6f1df941eb10163e3fdc5391ab5807aa46758d4258547c1f5ede31e6d9bfda8dd3"; };
"assert-plus@npm:1.0.0" = { filename = "assert-plus-npm-1.0.0-cac95ef098-19b4340cb8.zip"; sha512 = "19b4340cb8f0e6a981c07225eacac0e9d52c2644c080198765d63398f0075f83bbc0c8e95474d54224e297555ad0d631c1dcd058adb1ddc2437b41a6b424ac64"; };
"success-symbol@npm:0.1.0" = { filename = "success-symbol-npm-0.1.0-f9acf99da0-fd5138df4b.zip"; sha512 = "fd5138df4baf98d0018bad560188376b4323c27686268344a59439240384e0263a80e099a80dade92f8ff4bcfb795ddda35cb8cf725b19a4619ddcaefd3b669f"; };
"is-glob@npm:2.0.1" = { filename = "is-glob-npm-2.0.1-f316041d6e-089f5f9364.zip"; sha512 = "089f5f93640072491396a5f075ce73e949a90f35832b782bc49a6b7637d58e392d53cb0b395e059ccab70fcb82ff35d183f6f9ebbcb43227a1e02e3fed5430c9"; };
"promise-throttle@npm:1.1.2" = { filename = "promise-throttle-npm-1.1.2-0bc4fe7fea-9c147f7c4b.zip"; sha512 = "9c147f7c4be88590b8e42bc3ed159768515b6536e185ddc088b9d21cf59b0b10185e741efda475659417e7bd56db0226b5c202998ca925f918906473f4f003ed"; };
"arr-union@npm:3.1.0" = { filename = "arr-union-npm-3.1.0-853ada9729-b5b0408c6e.zip"; sha512 = "b5b0408c6eb7591143c394f3be082fee690ddd21f0fdde0a0a01106799e847f67fcae1b7e56b0a0c173290e29c6aca9562e82b300708a268bc8f88f3d6613cb9"; };
"is-valid-glob@npm:0.3.0" = { filename = "is-valid-glob-npm-0.3.0-c7df45b368-4c98457fc9.zip"; sha512 = "4c98457fc92d22772598fc59aafb7d9f95e0e431b65843871aa1826c4b4d411962b23cc86099f59a2770cd7ab17c2a71f3e78ca21da511f59aac6b365eceb90a"; };
"psl@npm:1.8.0" = { filename = "psl-npm-1.8.0-226099d70e-6150048ed2.zip"; sha512 = "6150048ed2da3f919478bee8a82f3828303bc0fc730fb015a48f83c9977682c7b28c60ab01425a72d82a2891a1681627aa530a991d50c086b48a3be27744bde7"; };
"minimist@npm:1.2.5" = { filename = "minimist-npm-1.2.5-ced0e1f617-86706ce5b3.zip"; sha512 = "86706ce5b36c16bfc35c5fe3dbb01d5acdc9a22f2b6cc810b6680656a1d2c0e44a0159c9a3ba51fb072bb5c203e49e10b51dcd0eec39c481f4c42086719bae52"; };
"ansi-wrap@npm:0.1.0" = { filename = "ansi-wrap-npm-0.1.0-75f177e1b6-f24f652a5e.zip"; sha512 = "f24f652a5e450c0561cbc7d298ffa62dcd33c72f9da34fd3c24538dbf82de8fc21b7f924dc30cd9d01360bd2893d1954f0a60eee0550ca629bb148dcbeef5c5b"; };
"is-extglob@npm:1.0.0" = { filename = "is-extglob-npm-1.0.0-6d00ab629f-5eea8517fe.zip"; sha512 = "5eea8517feeae5206547c0fc838c1416ec763b30093c286e1965a05f46b74a59ad391f912565f3b67c9c31cab4769ab9c35420e016b608acb47309be8d0d6e94"; };
"glob@npm:7.2.0" = { filename = "glob-npm-7.2.0-bb4644d239-78a8ea9423.zip"; sha512 = "78a8ea942331f08ed2e055cb5b9e40fe6f46f579d7fd3d694f3412fe5db23223d29b7fee1575440202e9a7ff9a72ab106a39fee39934c7bedafe5e5f8ae20134"; };
"asynckit@npm:0.4.0" = { filename = "asynckit-npm-0.4.0-c718858525-7b78c451df.zip"; sha512 = "7b78c451df768adba04e2d02e63e2d0bf3b07adcd6e42b4cf665cb7ce899bedd344c69a1dcbce355b5f972d597b25aaa1c1742b52cffd9caccb22f348114f6be"; };
"path-is-absolute@npm:1.0.1" = { filename = "path-is-absolute-npm-1.0.1-31bc695ffd-060840f92c.zip"; sha512 = "060840f92cf8effa293bcc1bea81281bd7d363731d214cbe5c227df207c34cd727430f70c6037b5159c8a870b9157cba65e775446b0ab06fd5ecc7e54615a3b8"; };
"once@npm:1.4.0" = { filename = "once-npm-1.4.0-ccf03ef07a-cd0a885013.zip"; sha512 = "cd0a88501333edd640d95f0d2700fbde6bff20b3d4d9bdc521bdd31af0656b5706570d6c6afe532045a20bb8dc0849f8332d6f2a416e0ba6d3d3b98806c7db68"; };
"minimatch@npm:3.0.4" = { filename = "minimatch-npm-3.0.4-6e76f51c23-66ac295f8a.zip"; sha512 = "66ac295f8a7b59788000ea3749938b0970344c841750abd96694f80269b926ebcafad3deeb3f1da2522978b119e6ae3a5869b63b13a7859a456b3408bd18a078"; };
"fs.realpath@npm:1.0.0" = { filename = "fs.realpath-npm-1.0.0-c8f05d8126-99ddea01a7.zip"; sha512 = "99ddea01a7e75aa276c250a04eedeffe5662bce66c65c07164ad6264f9de18fb21be9433ead460e54cff20e31721c811f4fb5d70591799df5f85dce6d6746fd0"; };
"inherits@npm:2.0.4" = { filename = "inherits-npm-2.0.4-c66b3957a0-4a48a73384.zip"; sha512 = "4a48a733847879d6cf6691860a6b1e3f0f4754176e4d71494c41f3475553768b10f84b5ce1d40fbd0e34e6bfbb864ee35858ad4dd2cf31e02fc4a154b724d7f1"; };
"asn1@npm:0.2.6" = { filename = "asn1-npm-0.2.6-bdd07356c4-39f2ae343b.zip"; sha512 = "39f2ae343b03c15ad4f238ba561e626602a3de8d94ae536c46a4a93e69578826305366dc09fbb9b56aec39b4982a463682f259c38e59f6fa380cd72cd61e493d"; };
"inflight@npm:1.0.6" = { filename = "inflight-npm-1.0.6-ccedb4b908-f4f76aa072.zip"; sha512 = "f4f76aa072ce19fae87ce1ef7d221e709afb59d445e05d47fba710e85470923a75de35bfae47da6de1b18afc3ce83d70facf44cfb0aff89f0a3f45c0a0244dfd"; };
"getpass@npm:0.1.7" = { filename = "getpass-npm-0.1.7-519164a3be-ab18d55661.zip"; sha512 = "ab18d55661db264e3eac6012c2d3daeafaab7a501c035ae0ccb193c3c23e9849c6e29b6ac762b9c2adae460266f925d55a3a2a3a3c8b94be2f222df94d70c046"; };
"extsprintf@npm:1.3.0" = { filename = "extsprintf-npm-1.3.0-61a92b324c-cee7a4a1e3.zip"; sha512 = "cee7a4a1e34cffeeec18559109de92c27517e5641991ec6bab849aa64e3081022903dd53084f2080d0d2530803aa5ee84f1e9de642c365452f9e67be8f958ce2"; };
"extsprintf@npm:1.4.1" = { filename = "extsprintf-npm-1.4.1-140b2f27ab-a2f29b2419.zip"; sha512 = "a2f29b241914a8d2bad64363de684821b6b1609d06ae68d5b539e4de6b28659715b5bea94a7265201603713b7027d35399d10b0548f09071c5513e65e8323d33"; };
"wrappy@npm:1.0.2" = { filename = "wrappy-npm-1.0.2-916de4d4b3-159da4805f.zip"; sha512 = "159da4805f7e84a3d003d8841557196034155008f817172d4e986bd591f74aa82aa7db55929a54222309e01079a65a92a9e6414da5a6aa4b01ee44a511ac3ee5"; };
"map-canvas@npm:0.1.5" = { filename = "map-canvas-npm-0.1.5-46acccc430-95f006e722.zip"; sha512 = "95f006e722a1de3e7639797db311ca7587d10fb2503c887151ee7d409bd0650b1250af449d2e943cb4444c4a24ccf50f92ccf5babbf7d7b2a99363b7e5d135ac"; };
"ansi-term@npm:0.0.2" = { filename = "ansi-term-npm-0.0.2-052bb240a0-01123e07bd.zip"; sha512 = "01123e07bdd8b25dac67ed5c7b374db629966dc57127eaedd708a18cbebab4e42abfb133d372609ae85dc45e2a71e16ea69c96236b61f11a2acff9ead743ba76"; };
"drawille-canvas-blessed-contrib@npm:0.1.3" = { filename = "drawille-canvas-blessed-contrib-npm-0.1.3-2e5f70b0b2-953416dc62.zip"; sha512 = "953416dc624185ed05a63ea2716010236828f964cc862578029d3e16b3a4b14e3018153f802c7b9f596957b307aa3c2ad190f64a00e7ff74f1c4b84d095864a7"; };
"brace-expansion@npm:1.1.11" = { filename = "brace-expansion-npm-1.1.11-fb95eb05ad-faf34a7bb0.zip"; sha512 = "faf34a7bb0c3fcf4b59c7808bc5d2a96a40988addf2e7e09dfbb67a2251800e0d14cd2bfc1aa79174f2f5095c54ff27f46fb1289fe2d77dac755b5eb3434cc07"; };
"marked-terminal@npm:4.2.0" = { filename = "marked-terminal-npm-4.2.0-efa6513dff-a68a4cfd22.zip"; sha512 = "a68a4cfd22b42f990a82e3234c68006ab4d1285a4a9bdd162f597740d9a55275c10c78ca21fa3927a76b2197589fe382e33af9baa2ccb2153812986c15aa73b8"; };
"chalk@npm:4.1.2" = { filename = "chalk-npm-4.1.2-ba8b67ab80-fe75c9d5c7.zip"; sha512 = "fe75c9d5c76a7a98d45495b91b2172fa3b7a09e0cc9370e5c8feb1c567b85c4288e2b3fded7cfdd7359ac28d6b3844feb8b82b8686842e93d23c827c417e83fc"; };
"ansi-styles@npm:4.3.0" = { filename = "ansi-styles-npm-4.3.0-245c7d42c7-513b44c3b2.zip"; sha512 = "513b44c3b2105dd14cc42a19271e80f386466c4be574bccf60b627432f9198571ebf4ab1e4c3ba17347658f4ee1711c163d574248c0c1cdc2d5917a0ad582ec4"; };
"supports-color@npm:7.2.0" = { filename = "supports-color-npm-7.2.0-606bfcf7da-3dda818de0.zip"; sha512 = "3dda818de06ebbe5b9653e07842d9479f3555ebc77e9a0280caf5a14fb877ffee9ed57007c3b78f5a6324b8dbeec648d9e97a24e2ed9fdb81ddc69ea07100f4a"; };
"term-canvas@npm:0.0.5" = { filename = "term-canvas-npm-0.0.5-b3b95b0ef9-36408f7525.zip"; sha512 = "36408f75257e8ae8d79c075c04e0b0367a89da5868f8bdc534bef6d4f1f6ca1492bb17a4f9b7c7c9ecfe8a415e3806d27b0be511696a1a99de10c3f9b72ca80c"; };
"memory-streams@npm:0.1.3" = { filename = "memory-streams-npm-0.1.3-8b67a57781-aebb6dc54c.zip"; sha512 = "aebb6dc54c35ff8e7fcbbffc736ae95938d9bb7ed66735b693ed18743fcc6268f64eaa80b2580a49c3c73ddc00cd880d5847f318997affe6d2a46b75365715f8"; };
"xml2js@npm:0.4.23" = { filename = "xml2js-npm-0.4.23-93a8b2e10b-ca0cf2dfbf.zip"; sha512 = "ca0cf2dfbf6deeaae878a891c8fbc0db6fd04398087084edf143cdc83d0509ad0fe199b890f62f39c4415cf60268a27a6aed0d343f0658f8779bd7add690fa98"; };
"memorystream@npm:0.3.1" = { filename = "memorystream-npm-0.3.1-ae973f1d16-f18b42440d.zip"; sha512 = "f18b42440d24d09516d01466c06adf797df7873f0d40aa7db02e5fb9ed83074e5e65412d0720901d7069363465f82dc4f8bcb44f0cde271567a61426ce6ca2e9"; };
"here@npm:0.0.2" = { filename = "here-npm-0.0.2-591dce7ef1-73531438cf.zip"; sha512 = "73531438cfe6919a12d350fdaa356d18b8ed6479a4bdeaa05d7fb91dafd9ff52d0c4bd41eb28c92bf27631da1f52f7c7c7a75263600686983f2c4b9d06833d60"; };
"gl-matrix@npm:2.8.1" = { filename = "gl-matrix-npm-2.8.1-289748ebea-20d13fd428.zip"; sha512 = "20d13fd428ea3021d625781e025132ff8ec264f4c05310bda9ad859535ab32fb505323486d2d5c51b5f715c2a9d059da588b66e8e2afdafdf1acc4f45629b7ff"; };
"marked@npm:2.1.3" = { filename = "marked-npm-2.1.3-24a375700c-21a5ecd494.zip"; sha512 = "21a5ecd4941bc760aba21dfd97185853ec3b464cf707ad971e3ddb3aeb2f44d0deeb36b0889932afdb6f734975a994d92f18815dd0fabadbd902bdaff997cc5b"; };
"concat-map@npm:0.0.1" = { filename = "concat-map-npm-0.0.1-85a921b7ee-902a9f5d89.zip"; sha512 = "902a9f5d8967a3e2faf138d5cb784b9979bad2e6db5357c5b21c568df4ebe62bcb15108af1b2253744844eb964fc023fbd9afbbbb6ddd0bcc204c6fb5b7bf3af"; };
"supports-hyperlinks@npm:2.2.0" = { filename = "supports-hyperlinks-npm-2.2.0-9b22a6271b-aef04fb41f.zip"; sha512 = "aef04fb41f4a67f1bc128f7c3e88a81b6cf2794c800fccf137006efe5bafde281da3e42e72bf9206c2fcf42e6438f37e3a820a389214d0a88613ca1f2d36076a"; };
"cardinal@npm:2.1.1" = { filename = "cardinal-npm-2.1.1-b77e7b28a7-e8d4ae4643.zip"; sha512 = "e8d4ae46439cf8fed481c0efd267711ee91e199aa7821a9143e784ed94a6495accd01a0b36d84d377e8ee2cc9928a6c9c123b03be761c60b805f2c026b8a99ad"; };
"balanced-match@npm:1.0.2" = { filename = "balanced-match-npm-1.0.2-a53c126459-9706c088a2.zip"; sha512 = "9706c088a283058a8a99e0bf91b0a2f75497f185980d9ffa8b304de1d9e58ebda7c72c07ebf01dadedaac5b2907b2c6f566f660d62bd336c3468e960403b9d65"; };
"escape-string-regexp@npm:1.0.5" = { filename = "escape-string-regexp-npm-1.0.5-3284de402f-6092fda75c.zip"; sha512 = "6092fda75c63b110c706b6a9bfde8a612ad595b628f0bd2147eea1d3406723020810e591effc7db1da91d80a71a737a313567c5abb3813e8d9c71f4aa595b410"; };
"color-convert@npm:2.0.1" = { filename = "color-convert-npm-2.0.1-79730e935b-79e6bdb9fd.zip"; sha512 = "79e6bdb9fd479a205c71d89574fccfb22bd9053bd98c6c4d870d65c132e5e904e6034978e55b43d69fcaa7433af2016ee203ce76eeba9cfa554b373e7f7db336"; };
"ansi-escapes@npm:4.3.2" = { filename = "ansi-escapes-npm-4.3.2-3ad173702f-93111c4218.zip"; sha512 = "93111c42189c0a6bed9cdb4d7f2829548e943827ee8479c74d6e0b22ee127b2a21d3f8b5ca57723b8ef78ce011fbfc2784350eb2bde3ccfccf2f575fa8489815"; };
"has-flag@npm:4.0.0" = { filename = "has-flag-npm-4.0.0-32af9f0536-261a135703.zip"; sha512 = "261a1357037ead75e338156b1f9452c016a37dcd3283a972a30d9e4a87441ba372c8b81f818cd0fbcd9c0354b4ae7e18b9e1afa1971164aef6d18c2b6095a8ad"; };
"readable-stream@npm:1.0.34" = { filename = "readable-stream-npm-1.0.34-db63158f3f-85042c537e.zip"; sha512 = "85042c537e4f067daa1448a7e257a201070bfec3dd2706abdbd8ebc7f3418eb4d3ed4b8e5af63e2544d69f88ab09c28d5da3c0b77dc76185fddd189a59863b60"; };
"core-util-is@npm:1.0.3" = { filename = "core-util-is-npm-1.0.3-ca74b76c90-9de8597363.zip"; sha512 = "9de8597363a8e9b9952491ebe18167e3b36e7707569eed0ebf14f8bba773611376466ae34575bca8cfe3c767890c859c74056084738f09d4e4a6f902b2ad7d99"; };
"node-emoji@npm:1.11.0" = { filename = "node-emoji-npm-1.11.0-dd2f09050c-e8c856c04a.zip"; sha512 = "e8c856c04a1645062112a72e59a98b203505ed5111ff84a3a5f40611afa229b578c7d50f1e6a7f17aa62baeea4a640d2e2f61f63afc05423aa267af10977fb2b"; };
"sax@npm:1.2.4" = { filename = "sax-npm-1.2.4-178f05f12f-d3df7d32b8.zip"; sha512 = "d3df7d32b897a2c2f28e941f732c71ba90e27c24f62ee918bd4d9a8cfb3553f2f81e5493c7f0be94a11c1911b643a9108f231dd6f60df3fa9586b5d2e3e9e1fe"; };
"buffers@npm:0.1.1" = { filename = "buffers-npm-0.1.1-59dbe6d7fb-ad6f8e483e.zip"; sha512 = "ad6f8e483efab39cefd92bdc04edbff6805e4211b002f4d1cfb70c6c472a61cc89fb18c37bcdfdd4ee416ca096e9ff606286698a7d41a18b539bac12fd76d4d5"; };
"redeyed@npm:2.1.1" = { filename = "redeyed-npm-2.1.1-7cbceb60bb-39a1426e37.zip"; sha512 = "39a1426e377727cfb47a0e24e95c1cf78d969fbc388dc1e0fa1e2ef8a8756450cefb8b0c2598f63b85f1a331986fca7604c0db798427a5775a1dbdb9c1291979"; };
"ansicolors@npm:0.3.2" = { filename = "ansicolors-npm-0.3.2-cc35882814-e84fae7ebc.zip"; sha512 = "e84fae7ebc27ac96d9dbb57f35f078cd6dde1b7046b0f03f73dcefc9fbb1f2e82e3685d083466aded8faf038f9fa9ebb408d215282bcd7aaa301d5ac3c486815"; };
"charm@npm:0.1.2" = { filename = "charm-npm-0.1.2-e4ee50a1a4-fe64983d7a.zip"; sha512 = "fe64983d7a87e7dacf225bd1fc10d34554110e128d3f3b8a91cfefb370b92211d0f1f7a9ff43df3ccfcb81d7f91525750b998519ab6b8e3c9dd249a3529ad783"; };
"xmlbuilder@npm:11.0.1" = { filename = "xmlbuilder-npm-11.0.1-b8b04dc929-7152695e16.zip"; sha512 = "7152695e16f1a9976658215abab27e55d08b1b97bca901d58b048d2b6e106b5af31efccbdecf9b07af37c8377d8e7e821b494af10b3a68b0ff4ae60331b415b0"; };
"isarray@npm:0.0.1" = { filename = "isarray-npm-0.0.1-92e37e0a70-49191f1425.zip"; sha512 = "49191f1425681df4a18c2f0f93db3adb85573bcdd6a4482539d98eac9e705d8961317b01175627e860516a2fc45f8f9302db26e5a380a97a520e272e2a40a8d4"; };
"color-name@npm:1.1.4" = { filename = "color-name-npm-1.1.4-025792b0ea-b044585952.zip"; sha512 = "b0445859521eb4021cd0fb0cc1a75cecf67fceecae89b63f62b201cca8d345baf8b952c966862a9d9a2632987d4f6581f0ec8d957dfacece86f0a7919316f610"; };
"string_decoder@npm:0.10.31" = { filename = "string_decoder-npm-0.10.31-851f3f7302-fe00f8e303.zip"; sha512 = "fe00f8e303647e5db919948ccb5ce0da7dea209ab54702894dd0c664edd98e5d4df4b80d6fabf7b9e92b237359d21136c95bf068b2f7760b772ca974ba970202"; };
"esprima@npm:4.0.1" = { filename = "esprima-npm-4.0.1-1084e98778-b45bc805a6.zip"; sha512 = "b45bc805a613dbea2835278c306b91aff6173c8d034223fa81498c77dcbce3b2931bf6006db816f62eacd9fd4ea975dfd85a5b7f3c6402cfd050d4ca3c13a628"; };
"bfx-api-node-models@npm:1.6.1" = { filename = "bfx-api-node-models-npm-1.6.1-58ecb01ab3-fe113a05c2.zip"; sha512 = "fe113a05c2f20c3824b2d4c6f3cc18eae893b85c86ddb7388a1a90f0c50f749572456573eb605b3c442b3f6c0ec6c6fa784006814152a328aa4296dc5746a20e"; };
"crc-32@npm:1.2.0" = { filename = "crc-32-npm-1.2.0-e56bb85839-7bcde8bea2.zip"; sha512 = "7bcde8bea262f6629ac3c70e20bdfa3d058dc77091705ce8620513f76f19b41fc273ddd65a716eef9b4e33fbb61ff7f9b266653d214319aef27e4223789c6b9e"; };
"printj@npm:1.1.2" = { filename = "printj-npm-1.1.2-5c18cf1e70-1c0c668445.zip"; sha512 = "1c0c66844545415e339356ad62009cdc467819817b1e0341aba428087a1414d46b84089edb4e77ef24705829f8aae6349724b9c7bd89d8690302b2de7a89b315"; };
"type-fest@npm:0.21.3" = { filename = "type-fest-npm-0.21.3-5ff2a9c6fd-e6b32a3b38.zip"; sha512 = "e6b32a3b3877f04339bae01c193b273c62ba7bfc9e325b8703c4ee1b32dc8fe4ef5dfa54bf78265e069f7667d058e360ae0f37be5af9f153b22382cd55a9afe0"; };
"to-file@npm:0.2.0" = { filename = "to-file-npm-0.2.0-994e48b9f6-60b8063501.zip"; sha512 = "60b8063501e7599686cd36e154570b364696e82d1dbcb4a8cf51d30e45732051fc8c954e44a833de2827a61772f1fa816130448cdd7268ab9f27918f8fd5d10d"; };
"file-contents@npm:0.2.4" = { filename = "file-contents-npm-0.2.4-5954aaa545-2487d56fec.zip"; sha512 = "2487d56fec6836f013f7a7eea0faa414047d38d6230422eff08f709c63b2b77f24e22910034f3b73703212f2776885161394980b9919459beaa7feac11a2f42b"; };
"file-contents@npm:0.3.2" = { filename = "file-contents-npm-0.3.2-238e6b92c8-6a28864ef0.zip"; sha512 = "6a28864ef06eff27f5a56adfa5cbf9e7e7cd57487d146c94293bdaeadb42bbc0ba80e9a7d577dc751ea405d2b19ae3564ec88131d7dfb4accb46be49889545aa"; };
"is-absolute@npm:0.2.6" = { filename = "is-absolute-npm-0.2.6-706ff06f01-3451cf0591.zip"; sha512 = "3451cf0591bb56c0837e8746d06662dd3afc277b76f6109e8446cb2a550f9d7d1dbd1e87b83c2e64d63327e0ee29d71ab19403376c84be712071309877d0a7d5"; };
"define-property@npm:0.2.5" = { filename = "define-property-npm-0.2.5-44a0da3575-85af107072.zip"; sha512 = "85af107072b04973b13f9e4128ab74ddfda48ec7ad2e54b193c0ffb57067c4ce5b7786a7b4ae1f24bd03e87c5d18766b094571810b314d7540f86d4354dbd394"; };
"isobject@npm:2.1.0" = { filename = "isobject-npm-2.1.0-2798cf0d94-811c6f5a86.zip"; sha512 = "811c6f5a866877d31f0606a88af4a45f282544de886bf29f6a34c46616a1ae2ed17076cc6bf34c0128f33eecf7e1fcaa2c82cf3770560d3e26810894e96ae79f"; };
"isarray@npm:1.0.0" = { filename = "isarray-npm-1.0.0-db4f547720-f032df8e02.zip"; sha512 = "f032df8e02dce8ec565cf2eb605ea939bdccea528dbcf565cdf92bfa2da9110461159d86a537388ef1acef8815a330642d7885b29010e8f7eac967c9993b65ab"; };
"resolve-dir@npm:0.1.1" = { filename = "resolve-dir-npm-0.1.1-0debfbb554-cc3e188593.zip"; sha512 = "cc3e1885938f8fe9656a6faa651e21730d369260e907b8dd7c847a4aa18db348ac08ee0dbf2d6f87e2ba08715fb109432ec773bbb31698381bd2a48c0ea66072"; };
"vinyl@npm:1.2.0" = { filename = "vinyl-npm-1.2.0-f1276fadff-0a382194fd.zip"; sha512 = "0a382194fd552a2aa9a21fdad7c8d3c8e32066a350b252a703f3c736f847b5c957b8ae7d621fd710805fa10d8a581eb3dae7bc2d98cdd74664b88820f1a79a77"; };
"lazy-cache@npm:0.2.7" = { filename = "lazy-cache-npm-0.2.7-8dd3e8d6b1-b4538aff20.zip"; sha512 = "b4538aff20db586c354f31de3ed59ea2c8d5dc4f01141bf49f07601e7ca0d7ed43a3f49362ade49b1e18ab1f3d121df0f2c9ea9b599b44dd54fb0c0db253c8b9"; };
"lazy-cache@npm:2.0.2" = { filename = "lazy-cache-npm-2.0.2-6f6bc0b22b-f4106a2834.zip"; sha512 = "f4106a28345b4b3b8e2dd544936ea5742bed650250d666f68e07bc7de55d04f75e750a36e2bf38ecb80e7520da95831e29dcdab608e3c32ca3189e6d8fb50e1f"; };
"is-utf8@npm:0.2.1" = { filename = "is-utf8-npm-0.2.1-46ab364e2f-167ccd2be8.zip"; sha512 = "167ccd2be869fc228cc62c1a28df4b78c6b5485d15a29027d3b5dceb09b383e86a3522008b56dcac14b592b22f0a224388718c2505027a994fd8471465de54b3"; };
"request-promise-core@npm:1.1.4" = { filename = "request-promise-core-npm-1.1.4-cb9fff6c90-c798bafd55.zip"; sha512 = "c798bafd552961e36fbf5023b1d081e81c3995ab390f1bc8ef38a711ba3fe4312eb94dbd61887073d7356c3499b9380947d7f62faa805797c0dc50f039425699"; };
"through2@npm:2.0.5" = { filename = "through2-npm-2.0.5-77d90f13cd-beb0f338aa.zip"; sha512 = "beb0f338aa2931e5660ec7bf3ad949e6d2e068c31f4737b9525e5201b824ac40cac6a337224856b56bd1ddd866334bbfb92a9f57cd6f66bc3f18d3d86fc0fe50"; };
"readable-stream@npm:2.3.7" = { filename = "readable-stream-npm-2.3.7-77b22a9818-e4920cf754.zip"; sha512 = "e4920cf7549a60f8aaf694d483a0e61b2a878b969d224f89b3bc788b8d920075132c4b55a7494ee944c7b6a9a0eada28a7f6220d80b0312ece70bbf08eeca755"; };
"safe-buffer@npm:5.1.2" = { filename = "safe-buffer-npm-5.1.2-c27fedf6c4-f2f1f7943c.zip"; sha512 = "f2f1f7943ca44a594893a852894055cf619c1fbcb611237fc39e461ae751187e7baf4dc391a72125e0ac4fb2d8c5c0b3c71529622e6a58f46b960211e704903c"; };
"string_decoder@npm:1.1.1" = { filename = "string_decoder-npm-1.1.1-e46a6c1353-9ab7e56f9d.zip"; sha512 = "9ab7e56f9d60a28f2be697419917c50cac19f3e8e6c28ef26ed5f4852289fe0de5d6997d29becf59028556f2c62983790c1d9ba1e2a3cc401768ca12d5183a5b"; };
"is-buffer@npm:1.1.6" = { filename = "is-buffer-npm-1.1.6-08199d9ccc-4a186d995d.zip"; sha512 = "4a186d995d8bbf9153b4bd9ff9fd04ae75068fe695d29025d25e592d9488911eeece84eefbd8fa41b8ddcc0711058a71d4c466dcf6f1f6e1d83830052d8ca707"; };
"ultron@npm:1.1.1" = { filename = "ultron-npm-1.1.1-193641dfec-aa7b5ebb1b.zip"; sha512 = "aa7b5ebb1b6e33287b9d873c6756c4b7aa6d1b23d7162ff25b0c0ce5c3c7e26e2ab141a5dc6e96c10ac4d00a372e682ce298d784f06ffcd520936590b4bc0653"; };
"is-descriptor@npm:0.1.6" = { filename = "is-descriptor-npm-0.1.6-15c7346839-0f780c1b46.zip"; sha512 = "0f780c1b46b465f71d970fd7754096ffdb7b69fd8797ca1f5069c163eaedcd6a20ec4a50af669075c9ebcfb5266d2e53c8b227e485eefdb0d1fee09aa1dd8ab6"; };
"is-relative@npm:0.2.1" = { filename = "is-relative-npm-0.2.1-1c1542a06d-9923fbec5f.zip"; sha512 = "9923fbec5fbd9354f757ff1a133638e7f9bb06f586b215dc747823fe90ba455c9392ac5b1e2cf0a5896138a5efd3ba35895116790e8737307dbd6e5398a50281"; };
"is-windows@npm:0.2.0" = { filename = "is-windows-npm-0.2.0-32c20e83a7-3df25afda2.zip"; sha512 = "3df25afda2fd9f3926b08cebacf1fc0a1fe7805a2cb73ef0f1b911c949e4e7648c4623979d74b4502bdd9af69471101eb6051b751595f7f88569148186cf7a7a"; };
"clone-stats@npm:0.0.1" = { filename = "clone-stats-npm-0.0.1-fcb0acb9e5-24a47ba6a4.zip"; sha512 = "24a47ba6a4619fdb2bc7ef1728ca06934c7ff986a93820b81da7018698de54eade10cd078b75a409563270aac17397691214b020057c7e7a9f515da13fd61e50"; };
"global-modules@npm:0.2.3" = { filename = "global-modules-npm-0.2.3-36612c55cb-3801788df5.zip"; sha512 = "3801788df54897d994c9c8f3d09f253d1379cd879ae61fcddbcc3ecdfdf6fe23a1edb983e8d4dd24cebf7e49823752e1cd29a2d33bdb4de587de8b4a85b17e24"; };
"set-getter@npm:0.1.1" = { filename = "set-getter-npm-0.1.1-85070f31a6-04bc8ffff2.zip"; sha512 = "04bc8ffff286d7b36a3adc675d2858db3d6768f0290dce98ca5d481d5361936f4fa1e2570833de3511424adf534fc9e48f4b420163906b0d6ca45f38074f5108"; };
"expand-tilde@npm:1.2.2" = { filename = "expand-tilde-npm-1.2.2-9ff99585a9-18051cd104.zip"; sha512 = "18051cd104977bc06e2bb1347db9959b90504437beea0de6fd287a3c8c58b41e2330337bd189cfca2ee4be6bda9bf045f8c07daf23e622f85eb6ee1c420619a0"; };
"async-array-reduce@npm:0.2.1" = { filename = "async-array-reduce-npm-0.2.1-f54d0d684f-ecc15c7b95.zip"; sha512 = "ecc15c7b9580d408ff829f1bd29b90c4e2127892f9da7321c33e4c0adc298e3747f916c87db1049962aa6ed2b740d60963b8542e64e31ebe15c0d88821338e8b"; };
"clone@npm:1.0.4" = { filename = "clone-npm-1.0.4-a610fcbcf9-d06418b733.zip"; sha512 = "d06418b7335897209e77bdd430d04f882189582e67bd1f75a04565f3f07f5b3f119a9d670c943b6697d0afb100f03b866b3b8a1f91d4d02d72c4ecf2bb64b5dd"; };
"xtend@npm:4.0.2" = { filename = "xtend-npm-4.0.2-7f2375736e-ac5dfa738b.zip"; sha512 = "ac5dfa738b21f6e7f0dd6e65e1b3155036d68104e67e5d5d1bde74892e327d7e5636a076f625599dc394330a731861e87343ff184b0047fef1360a7ec0a5a36a"; };
"process-nextick-args@npm:2.0.1" = { filename = "process-nextick-args-npm-2.0.1-b8d7971609-1d38588e52.zip"; sha512 = "1d38588e520dab7cea67cbbe2efdd86a10cc7a074c09657635e34f035277b59fbb57d09d8638346bf7090f8e8ebc070c96fa5fd183b777fff4f5edff5e9466cf"; };
"kind-of@npm:5.1.0" = { filename = "kind-of-npm-5.1.0-ce82f43eaa-f2a0102ae0.zip"; sha512 = "f2a0102ae0cf19c4a953397e552571bad2b588b53282874f25fca7236396e650e2db50d41f9f516bd402536e4df968dbb51b8e69e4d5d4a7173def78448f7bab"; };
"to-object-path@npm:0.3.0" = { filename = "to-object-path-npm-0.3.0-241b5ffa9c-9425effee5.zip"; sha512 = "9425effee5b43e61d720940fa2b889623f77473d459c2ce3d4a580a4405df4403eec7be6b857455908070566352f9e2417304641ed158dda6f6a365fe3e66d70"; };
"kind-of@npm:3.2.2" = { filename = "kind-of-npm-3.2.2-7deaffa5f9-e898df8ca2.zip"; sha512 = "e898df8ca2f31038f27d24f0b8080da7be274f986bc6ed176f37c77c454d76627619e1681f6f9d2e8d2fd7557a18ecc419a6bb54e422abcbb8da8f1a75e4b386"; };
"os-homedir@npm:1.0.2" = { filename = "os-homedir-npm-1.0.2-01f82faa88-af609f5a7a.zip"; sha512 = "af609f5a7ab72de2f6ca9be6d6b91a599777afc122ac5cad47e126c1f67c176fe9b52516b9eeca1ff6ca0ab8587fe66208bc85e40a3940125f03cdb91408e9d2"; };
"is-unc-path@npm:0.1.2" = { filename = "is-unc-path-npm-0.1.2-7dcfdf64ad-47fd6f1829.zip"; sha512 = "47fd6f18294d9b107683322a4a659c1bf83f3a98c8e751c449e3b6d21def8d1f5b910e7e9ce28d08c3bb2897d5d494ebab5bcc224f328624d2a6d24d0a8d1e9b"; };
"fs-exists-sync@npm:0.1.0" = { filename = "fs-exists-sync-npm-0.1.0-c8642ca841-850a0d6e4c.zip"; sha512 = "850a0d6e4c03a7bd2fd25043f77cd9d6be9c3b48bb99308bcfe9c94f3f92f65f2cd3fa036e13a1b0ba7a46d2e58792f53e578f01d75fbdcd56baeb9eed63b705"; };
"is-data-descriptor@npm:0.1.4" = { filename = "is-data-descriptor-npm-0.1.4-6f53f71c67-5c622e078b.zip"; sha512 = "5c622e078ba933a78338ae398a3d1fc5c23332b395312daf4f74bab4afb10d061cea74821add726cb4db8b946ba36217ee71a24fe71dd5bca4632edb7f6aad87"; };
"unc-path-regex@npm:0.1.2" = { filename = "unc-path-regex-npm-0.1.2-53c3343ef3-a05fa2006b.zip"; sha512 = "a05fa2006bf4606051c10fc7968f08ce7b28fa646befafa282813aeb1ac1a56f65cb1b577ca7851af2726198d59475bb49b11776036257b843eaacee2860a4ec"; };
"bfx-hf-util@https://github.com/bitfinexcom/bfx-hf-util.git#commit=8f75768fc0324f300b7ad377e201212c54109887" = { filename = "bfx-hf-util-https-0089ab1032-b1d4b54616.zip"; sha512 = "b1d4b54616a7c40742e3c3de347eb8bf1035eb80e22363b92f9e8c19a0feec7d6bcebdf61607d769512459d5e64836571249d344bcea4b0799f27b3b7b48ce50"; };
"drawille-blessed-contrib@npm:1.0.0" = { filename = "drawille-blessed-contrib-npm-1.0.0-dee17486f6-824f2c78ea.zip"; sha512 = "824f2c78ea588d8b11ccc302a9855e53182b1d9f9695dc07ffab845e832fbfc3253ca996c5dcc10e671bbed9715f2daaf179ccba8860c8df2b10c4ae83ec2ddc"; };
"is-accessor-descriptor@npm:0.1.6" = { filename = "is-accessor-descriptor-npm-0.1.6-41c495d517-3d629a086a.zip"; sha512 = "3d629a086a9585bc16a83a8e8a3416f400023301855cafb7ccc9a1d63145b7480f0ad28877dcc2cce09492c4ec1c39ef4c071996f24ee6ac626be4217b8ffc8a"; };
"stackman@npm:4.0.1" = { filename = "stackman-npm-4.0.1-73e056ebed-c6c725fa5a.zip"; sha512 = "c6c725fa5a710e113718a38d9832a5b10e41f86941208ce50b5d3339c32bc9340abc4bac05e37c52213f807de7f2d923a231f24cd36b5b8b5968a80a8f5af064"; };
"bresenham@npm:0.0.3" = { filename = "bresenham-npm-0.0.3-e8400b1739-f40703d57d.zip"; sha512 = "f40703d57d1587aa1b0923c016c5fa1fcc354c5b49cbb205e613c223b9e09a4dd80cd990c3cc112ae4ff6704195b0255f9d677c2e8b199545f058b396f52706c"; };
"async-cache@npm:1.1.0" = { filename = "async-cache-npm-1.1.0-c3e269282f-3f55cc78b3.zip"; sha512 = "3f55cc78b3ddc745b6604dd144fc7bca2e21c7ba4c5ea18d312234dc625133511723dff6c71b2283582421f95d591bdb24bf89ce4c4869151e4ecedbdad4acf2"; };
"load-source-map@npm:1.0.0" = { filename = "load-source-map-npm-1.0.0-1a5c0200e9-11089439b9.zip"; sha512 = "11089439b9f6aec2e4f9a816315239548cff0f3b06f7c48380ee2c94b38ba518fb29ee4cd6fc96b94019ce5349062a02cff286dc06c750f261dfe8754391daf7"; };
"after-all-results@npm:2.0.0" = { filename = "after-all-results-npm-2.0.0-20af503b94-24de1c95b6.zip"; sha512 = "24de1c95b6387f6d5f0e6f5a638d77fbf565647ee0bd3c4a0d0522b877db77c81cd2e05adf581d164a7ddf61698bbb46375a4028fb5fc09ffa7e71b7d08cf9a4"; };
"lru-cache@npm:4.1.5" = { filename = "lru-cache-npm-4.1.5-ede304cc43-4bb4b58a36.zip"; sha512 = "4bb4b58a36cd7dc4dcec74cbe6a8f766a38b7426f1ff59d4cf7d82a2aa9b9565cd1cb98f6ff60ce5cd174524868d7bc9b7b1c294371851356066ca9ac4cf135a"; };
"in-publish@npm:2.0.1" = { filename = "in-publish-npm-2.0.1-5a970fa809-5efde2992a.zip"; sha512 = "5efde2992a1e76550614a5a2c51f53669d9f3ee3a11d364de22b0c77c41de0b87c52c4c9b04375eaa276761b1944dd2b166323894d2344192328ffe85927ad38"; };
"source-map@npm:0.5.7" = { filename = "source-map-npm-0.5.7-7c3f035429-5dc2043b93.zip"; sha512 = "5dc2043b93d2f194142c7f38f74a24670cd7a0063acdaf4bf01d2964b402257ae843c2a8fa822ad5b71013b5fcafa55af7421383da919752f22ff488bc553f4d"; };
"semver@npm:5.7.1" = { filename = "semver-npm-5.7.1-40bcea106b-57fd0acfd0.zip"; sha512 = "57fd0acfd0bac382ee87cd52cd0aaa5af086a7dc8d60379dfe65fea491fb2489b6016400813930ecd61fd0952dae75c115287a1b16c234b1550887117744dfaf"; };
"yallist@npm:2.1.2" = { filename = "yallist-npm-2.1.2-2e38c366a3-9ba9940920.zip"; sha512 = "9ba99409209f485b6fcb970330908a6d41fa1c933f75e08250316cce19383179a6b70a7e0721b89672ebb6199cc377bf3e432f55100da6a7d6e11902b0a642cb"; };
"pseudomap@npm:1.0.2" = { filename = "pseudomap-npm-1.0.2-0d0e40fee0-856c0aae0f.zip"; sha512 = "856c0aae0ff2ad60881168334448e898ad7a0e45fe7386d114b150084254c01e200c957cf378378025df4e052c7890c5bd933939b0e0d2ecfcc1dc2f0b2991f5"; };
"strip-bom-buffer@npm:0.1.1" = { filename = "strip-bom-buffer-npm-0.1.1-f4ce096e03-376e119520.zip"; sha512 = "376e11952050defce7f3e4bc5a40ce31ed4c9ce757ccb1fc56f40a9edab369810e71b8f7b8471a1672cbcf0a77a4dca133819bad93111b3f87c266eacbe069ff"; };
"file-stat@npm:0.1.3" = { filename = "file-stat-npm-0.1.3-97f3c7cda7-647c4fdd09.zip"; sha512 = "647c4fdd09e32cff88645f79a107ebce94817ee0d54214b3d130b64b8873525101fce745d729e633da6b7b42e4f6a367311b5ebd78c65a569bf73d10e18763a0"; };
"file-stat@npm:0.2.3" = { filename = "file-stat-npm-0.2.3-18ea6bff4c-331cb7430a.zip"; sha512 = "331cb7430ac0919e9b43db065794678f707155c164bae4413df00680652c3c8f19b0fab02568b3b6c39622e5b1687a5cc6edd949bab3f29589bca9b989f86f98"; };
"replace-ext@npm:0.0.1" = { filename = "replace-ext-npm-0.0.1-52ef533d9f-af6c5df587.zip"; sha512 = "af6c5df587c6e6f47b380ea5762457ec471be2fd4920acd943c61b68fd548f81e1e348219192b2a3db633b8e392be24206ba073498d3c146dca7f1b7e46478c5"; };
"strip-bom-string@npm:0.1.2" = { filename = "strip-bom-string-npm-0.1.2-5b8e2e3d81-ad184884ad.zip"; sha512 = "ad184884add5aab9fb82203e7afe5e057cd3dc562e328a14e45d608acd04ca7973d4533ae6aa1198a3e6bd036a2a707890b42cbb4dfe221bf3bdd06cc6d1aaed"; };
"util-deprecate@npm:1.0.2" = { filename = "util-deprecate-npm-1.0.2-e3fe1a219c-474acf1146.zip"; sha512 = "474acf1146cb2701fe3b074892217553dfcf9a031280919ba1b8d651a068c9b15d863b7303cb15bd00a862b498e6cf4ad7b4a08fb134edd5a6f7641681cb54a2"; };
"global-prefix@npm:0.1.5" = { filename = "global-prefix-npm-0.1.5-1fd688e1ae-ea1b818a18.zip"; sha512 = "ea1b818a1851655ebb2341cdd5446da81c25f31ca6f0ac358a234cbed5442edc1bfa5628771466988d67d9fcc6ad09ca0e68a8d3d7e3d92f7de3aec87020e183"; };
"ini@npm:1.3.8" = { filename = "ini-npm-1.3.8-fb5040b4c0-dfd98b0ca3.zip"; sha512 = "dfd98b0ca3a4fc1e323e38a6c8eb8936e31a97a918d3b377649ea15bdb15d481207a0dda1021efbd86b464cae29a0d33c1d7dcaf6c5672bee17fa849bc50a1b3"; };
"homedir-polyfill@npm:1.0.3" = { filename = "homedir-polyfill-npm-1.0.3-da1a29ce00-18dd4db870.zip"; sha512 = "18dd4db87052c6a2179d1813adea0c4bfcfa4f9996f0e226fefb29eb3d548e564350fa28ec46b0bf1fbc0a1d2d6922ceceb80093115ea45ff8842a4990139250"; };
"which@npm:1.3.1" = { filename = "which-npm-1.3.1-f0ebb8bdd8-f2e185c624.zip"; sha512 = "f2e185c6242244b8426c9df1510e86629192d93c1a986a7d2a591f2c24869e7ffd03d6dac07ca863b2e4c06f59a4cc9916c585b72ee9fa1aa609d0124df15e04"; };
"parse-passwd@npm:1.0.0" = { filename = "parse-passwd-npm-1.0.0-ace6effa1d-4e55e0231d.zip"; sha512 = "4e55e0231d58f828a41d0f1da2bf2ff7bcef8f4cb6146e69d16ce499190de58b06199e6bd9b17fbf0d4d8aef9052099cdf8c4f13a6294b1a522e8e958073066e"; };
"isexe@npm:2.0.0" = { filename = "isexe-npm-2.0.0-b58870bd2e-26bf6c5480.zip"; sha512 = "26bf6c5480dda5161c820c5b5c751ae1e766c587b1f951ea3fcfc973bafb7831ae5b54a31a69bd670220e42e99ec154475025a468eae58ea262f813fdc8d1c62"; };
"error-callsites@npm:2.0.4" = { filename = "error-callsites-npm-2.0.4-e50afef58d-977ef7d8bd.zip"; sha512 = "977ef7d8bdd5e040d9bc895e6f1bff736c75029a4d031d84d1ffb0ad50ee2d99e8417073dbc8e5ae547b6e8661037d785ab26022357361443718083097a6e9ff"; };
};

in optionalOverride overrideAttrs project
