// console.log(require('starkware-crypto-cpp-node'))
// require('ramda')
// console.log('node-module-test')
// require('node-module-test')
console.log('node-module-test-dev')
require('node-module-test-dev')
console.log('node-module-test')
require('node-module-test')
require('node-module-test-test')
// require('node-module-test-local')

// console.log('@adrian-gierakowski/private-repo-test')
// require('@adrian-gierakowski/private-repo-test')

// console.log('private-repo-test-git')
// require('private-repo-test-git')
